"""Go ソース生成用の純粋関数群.

`GoStyle` で出力スタイル (パディング/コメントキー/import 形式など) をスイッチし、
個々の `render_*` 関数は副作用なく行のリストを返す。Runner はこれらを組み合わせて
1 ファイル分の文字列を組み立てる。
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

DEFAULT_HEADER = "// Code generated by scripts/generate_types.py; DO NOT EDIT."

# 型文字列内の部分一致 → import パス。先勝ちではなく和集合として扱う。
DEFAULT_IMPORT_PATTERNS: dict[str, str] = {
    "time.": "time",
    "json.RawMessage": "encoding/json",
    "civil.": "cloud.google.com/go/civil",
}


@dataclass
class GoConstStyle:
    """`const ( ... )` ブロックの出力スタイル."""

    type_annotation: bool = False
    """`Name Type = "x"` の形で型注釈を付けるか. card: True, shop/support: False."""

    quote_string_only: bool = False
    """True の場合、`type: string` のみクォートし他は素の値で出す. shop/support: True."""

    default_type: str = "string"
    """YAML で `type:` を省略したときに仮定する型名."""


@dataclass
class GoStyle:
    """Go 出力スタイルのリポ別差分を吸収する設定束."""

    header: str = DEFAULT_HEADER

    # ── imports ──
    import_patterns: dict[str, str] = field(
        default_factory=lambda: dict(DEFAULT_IMPORT_PATTERNS)
    )
    use_inline_single_import: bool = False
    """import が 1 件のとき `import "x"` の単行形にする. matchmaking: True."""

    # ── 型コメント ──
    type_comment_key: str = "comment"
    """型レベルのコメントを取り出す YAML キー. matchmaking: "doc"."""
    type_comment_multiline: bool = False
    """型コメントを改行で割って複数行 `//` で出すか. matchmaking/shop/support: True."""

    # ── フィールド ──
    field_comment_key: str = "comment"
    """フィールドコメントを取り出す YAML キー. matchmaking: "doc"."""
    field_comment_position: str = "inline"
    """`inline` (型の後ろに ` // x`) or `above` (フィールド上に別行で) ."""
    field_align: bool = True
    """フィールドの name/type をパディング揃えするか. matchmaking: False."""
    field_extra_tag_key: str | None = None
    """追加の生タグ文字列を取り出すフィールドキー. matchmaking: "tag"."""

    # ── タグ ──
    tag_keys: tuple[str, ...] = ("json",)
    """フィールドの YAML キー → struct tag に転写する順. emit_tags は GoTarget 側で上書き可能."""

    # ── 定数 ──
    const_style: GoConstStyle = field(default_factory=GoConstStyle)


# ─── 低レベル: 型/フィールド/import 解析 ────────────────────


def resolve_auto_imports(
    types: list[dict[str, Any]],
    patterns: dict[str, str],
) -> set[str]:
    """型定義群から、フィールド型文字列に基づく必要 import パスを集める."""
    imports: set[str] = set()
    for td in types:
        for field_def in td.get("fields", []):
            type_str = str(field_def.get("type", ""))
            for needle, import_path in patterns.items():
                if needle in type_str:
                    imports.add(import_path)
    return imports


# ─── 低レベル: ブロック単位レンダリング ────────────────────


def render_import_block(imports: set[str], style: GoStyle) -> list[str]:
    """import 集合を Go の import ブロック行に整形する.

    `style.use_inline_single_import` が True かつ要素 1 件のときは
    `import "x"` 1 行で返す (matchmaking 互換)。
    """
    if not imports:
        return []
    if style.use_inline_single_import and len(imports) == 1:
        only = next(iter(imports))
        return [f'import "{only}"', ""]

    std = sorted(i for i in imports if "." not in i.split("/", 1)[0])
    ext = sorted(i for i in imports if "." in i.split("/", 1)[0])
    lines: list[str] = ["import ("]
    for imp in std:
        lines.append(f'\t"{imp}"')
    if std and ext:
        lines.append("")
    for imp in ext:
        lines.append(f'\t"{imp}"')
    lines.append(")")
    lines.append("")
    return lines


def render_const_block(const_def: dict[str, Any], style: GoConstStyle) -> list[str]:
    """`{type: ..., values: [...]}` 1 ブロックを const ( ... ) 行群にする."""
    type_name = const_def.get("type", style.default_type)
    values = const_def.get("values", [])
    if not values:
        return []
    lines: list[str] = ["const ("]
    for v in values:
        name = v["name"]
        value = v["value"]
        if style.type_annotation:
            lines.append(f'\t{name} {type_name} = "{value}"')
        else:
            if not style.quote_string_only or type_name == "string":
                lines.append(f'\t{name} = "{value}"')
            else:
                lines.append(f"\t{name} = {value}")
    lines.append(")")
    lines.append("")
    return lines


def render_type_aliases(aliases: list[dict[str, Any]]) -> list[str]:
    """`type Alias = Base` を一塊で並べる."""
    if not aliases:
        return []
    lines = [f"type {a['name']} = {a['base']}" for a in aliases]
    lines.append("")
    return lines


def _render_type_comment(td: dict[str, Any], style: GoStyle) -> list[str]:
    text = td.get(style.type_comment_key)
    if not text:
        return []
    text_str = str(text).rstrip("\n")
    if style.type_comment_multiline:
        out: list[str] = []
        for line in text_str.splitlines():
            out.append(f"// {line}" if line else "//")
        return out
    return [f"// {text_str}"]


def _build_field_tag(
    field_def: dict[str, Any],
    emit_tags: tuple[str, ...],
    style: GoStyle,
) -> str:
    """`json:"x" db:"y"` 形式のタグ本文 (バッククォートなし) を組み立てる."""
    parts: list[str] = []
    for key in emit_tags:
        if key in field_def:
            parts.append(f'{key}:"{field_def[key]}"')
    if style.field_extra_tag_key:
        extra = field_def.get(style.field_extra_tag_key)
        if extra:
            parts.append(str(extra))
    return " ".join(parts)


def render_struct(
    type_def: dict[str, Any],
    style: GoStyle,
    emit_tags: tuple[str, ...] | None = None,
) -> list[str]:
    """1 つの struct 定義を行リストに整形する."""
    tags_to_emit = emit_tags if emit_tags is not None else style.tag_keys

    lines: list[str] = []
    lines.extend(_render_type_comment(type_def, style))
    lines.append(f"type {type_def['name']} struct {{")

    fields = type_def.get("fields", [])
    if style.field_align and fields:
        max_name_len = max(len(f["name"]) for f in fields)
        max_type_len = max(len(str(f["type"])) for f in fields)
    else:
        max_name_len = 0
        max_type_len = 0

    for field_def in fields:
        fname = field_def["name"]
        ftype = str(field_def["type"])
        comment = field_def.get(style.field_comment_key)
        tag_body = _build_field_tag(field_def, tags_to_emit, style)

        if style.field_comment_position == "above" and comment:
            for cl in str(comment).rstrip("\n").splitlines():
                lines.append(f"\t// {cl}" if cl else "\t//")

        if style.field_align:
            name_pad = " " * (max_name_len - len(fname) + 1)
            type_pad = " " * (max_type_len - len(ftype) + 1)
            if tag_body:
                line = f"\t{fname}{name_pad}{ftype}{type_pad}`{tag_body}`"
            else:
                line = f"\t{fname}{name_pad}{ftype}"
        else:
            if tag_body:
                line = f"\t{fname} {ftype} `{tag_body}`"
            else:
                line = f"\t{fname} {ftype}"

        if style.field_comment_position == "inline" and comment:
            line += f" // {comment}"

        lines.append(line)

    lines.append("}")
    lines.append("")
    return lines


# ─── ファイル単位レンダリング ────────────────────────────────


def render_go_file(
    *,
    package: str,
    types: list[dict[str, Any]],
    style: GoStyle,
    constants: list[dict[str, Any]] | None = None,
    type_aliases: list[dict[str, Any]] | None = None,
    extra_imports: set[str] | None = None,
    emit_tags: tuple[str, ...] | None = None,
    trailing_blank_line: bool = False,
) -> str:
    """1 Go ファイル分の最終出力文字列を組み立てる.

    - `extra_imports`: YAML の `imports:` セクションなど、自動検出に加えて常に出すもの。
    - `emit_tags`: 個々の struct field でどの YAML キーをタグ化するか (target 別に切替)。
    - `trailing_blank_line`: 末尾に余計な空行を残すか。多くのリポは "rstrip + \\n" で末尾整形するが、
       一部 (shop/support/account/scenario/card) は末尾空行ありの実装になっているので互換用。
    """
    lines: list[str] = [style.header, "", f"package {package}", ""]

    auto = resolve_auto_imports(types, style.import_patterns)
    imports = (extra_imports or set()) | auto
    lines.extend(render_import_block(imports, style))

    if type_aliases:
        lines.extend(render_type_aliases(type_aliases))

    if constants:
        for const_def in constants:
            lines.extend(render_const_block(const_def, style.const_style))

    for td in types:
        lines.extend(render_struct(td, style, emit_tags=emit_tags))

    body = "\n".join(lines)
    if trailing_blank_line:
        return body + "\n"
    return body.rstrip() + "\n"
