// Code generated by generate_from_yaml.py; DO NOT EDIT.

package cardno

// SHE（Smile Horizon Express）
const (
	SHEComputeEkubo           int64 = 1    // えくぼ
	SHEContainerAlligator     int64 = 3    // アリゲーテナ
	SHEOrchestratorKujirantis int64 = 4    // クジラの統率者<クジランティス>
	SHEMLRoughmaker           int64 = 5    // ラフメイカー
	SHEServerlessRamune       int64 = 6    // むらた
	SHERDBAdeliece            int64 = 7    // アデリース
	SHEDistributedDBOoroba    int64 = 8    // オオロバ
	SHEStorageEris            int64 = 9    // えりり
	SHEDBDinosaur             int64 = 10   // ダイノ
	SHECacheMerry             int64 = 11   // メリーモ
	SHEPipeline               int64 = 12   // SHE Pipeline
	SHEFront                  int64 = 13   // SHE Front
	SHEGuard                  int64 = 14   // SHE Guard
	SHEFirewall               int64 = 15   // SHE Firewall
	SHEQueue                  int64 = 16   // SHE Queue
	SHEGateway                int64 = 17   // SHE Gateway
	SHEKeys                   int64 = 18   // SHE Keys
	SHEFormation              int64 = 19   // SHE Formation
	SHEMarketplace            int64 = 20   // SHE Marketplace
	SHERyoukinMitsumori       int64 = 21   // SHE 料金見積もり
	SmileRecovery             int64 = 22   // Smile Recovery
	SHEEcosystem              int64 = 118  // SHE Ecosystem
	SHESmileHorizonExpress    int64 = 121  // SHE Smile Horizon Express
	SHECacheDakkun            int64 = 124  // だっくん
	SHEBlockStorage           int64 = 131  // SHE Block Storage
)

// 天気使い
const (
	TenkiVMSora             int64 = 23   // ソラ
	TenkiPaaSAsagiri        int64 = 24   // アサギリ
	TenkiContainerKouten    int64 = 25   // コウテン
	TenkiOrchestratorKusoku int64 = 26   // 空即蒼色
	TenkiAIOpener           int64 = 27   // 智の解放者<オープナー>
	TenkiFunctionsRai       int64 = 28   // ライ
	TenkiRDBShigure         int64 = 29   // シグレ
	TenkiDBHayate           int64 = 30   // ハヤテ
	TenkiStorageFubuki      int64 = 31   // フブキ
	TenkiDBCosmo            int64 = 32   // 百花の天穹<コスモ>
	TenkiCacheReiu          int64 = 33   // シュウウ
	TenkiDevOps             int64 = 34   // 天気使い DevOps
	TenkiCDN                int64 = 35   // 天気使い CDN
	TenkiFunnel             int64 = 36   // 天気使い ファンネル
	TenkiProtection         int64 = 37   // 天気使い Protection
	TenkiBackup             int64 = 38   // 天気使い Backup
	TenkiEntra              int64 = 39   // 天気使い 空の入口
	TenkiVault              int64 = 40   // 天気使い Vault
	TenkiRecovery           int64 = 41   // 天気使い Recovery
	TenkiTemplate           int64 = 42   // 天気使い Template
	TenkiMigration          int64 = 43   // 天気使い Migration
	TenkiPolicy             int64 = 44   // 天気使い Policy
	TenkiOmamoriGasa        int64 = 45   // 天気使い お守り傘
	TenkiTraffic            int64 = 46   // 天気使い Traffic
	TenkiBlockStorage       int64 = 132  // 天気使い ブロックストレージ
)

// しゅがーらぼ
const (
	SugarComputeConfettiito  int64 = 47   // コンピエッタ
	SugarSpotSponjit         int64 = 48   // スポンジット
	SugarContainerClan       int64 = 49   // クラン
	SugarOrchestratorKuchen  int64 = 50   // クーヘンバウムティス
	SugarAIButterKun         int64 = 51   // バター君
	SugarAIDrTensorbe        int64 = 52   // Dr. テンソルベ
	SugarFunctionsClan       int64 = 53   // クラン
	SugarRDBEclairL          int64 = 54   // エクレアーエル
	SugarDistributedDBPinapo int64 = 55   // スーパーバナナ
	SugarStorageSchtrenge    int64 = 56   // シュトレーンジ
	SugarDBToastoa           int64 = 57   // トーストア
	SugarDWIcecream          int64 = 58   // アイスクエリム
	SugarBuild               int64 = 59   // しゅがーらぼ Build
	SugarCDN                 int64 = 60   // しゅがーらぼ CDN
	SugarIcecreamAnalytics   int64 = 61   // しゅがーらぼ アイスクエリム Analytics
	SugarProfiler            int64 = 62   // しゅがーらぼ Profiler
	SugarPakupakuSable       int64 = 63   // しゅがーらぼ ぱくぱくサブレ
	SugarDangoFlow           int64 = 64   // しゅがーらぼ だんごフロー
	SugarDeployment          int64 = 65   // しゅがーらぼ Deployment
	SugarButterKunBatch      int64 = 66   // しゅがーらぼ バター君 Batch
	SugarKnowledge           int64 = 67   // しゅがーらぼ Knowledge
	SugarErrorBudget         int64 = 68   // しゅがーらぼ Error Budget
	SugarCacheMeringue       int64 = 125  // メレンゲスト
	SugarBlockStorage        int64 = 133  // しゅがーらぼ ブロックストレージ
)

// 調律部（チューナーズ）
const (
	TunersComputeKantata        int64 = 70   // コンタータ
	TunersBareMetal             int64 = 72   // ベル太
	TunersContainerTena         int64 = 73   // テナ
	TunersOrchestratorConductis int64 = 74   // コンダクティス
	TunersFunctionsFanfare      int64 = 75   // ファンファーレクション
	TunersLowCodeApietta        int64 = 76   // アピエッタ
	TunersDBOtonmajutsushi      int64 = 77   // 音の魔術師〈マジシャン・オブ・ミュージック〉
	TunersDBExanotes            int64 = 78   // エクサノーツ
	TunersStorageScourge        int64 = 79   // スコアージ
	TunersCacheCaprish          int64 = 81   // カプリッシュ
	TunersDevOps                int64 = 82   // 調律部 DevOps
	TunersGuard                 int64 = 83   // 調律部 Guard
	TunersWAF                   int64 = 84   // 調律部 WAF
	TunersNotesGuard            int64 = 85   // 調律部 ノーツガード
	TunersRAC                   int64 = 86   // 調律部 リアル・アンサンブル・クラスター
	TunersLicense               int64 = 89   // 調律部 License
	TunersFailback              int64 = 90   // 調律部 Failback
	TunersBlockVolume           int64 = 134  // 調律部 Block Volume
)

// Neutral
const (
	NeutralLoadBalancer     int64 = 91   // ロードバランサー
	NeutralAutoScaler       int64 = 92   // オートスケーラー
	NeutralPrivateSubnet    int64 = 93   // プライベートサブネット
	NeutralMultiAZ          int64 = 94   // マルチ AZ
	NeutralISMS             int64 = 96   // ISMS認証
	NeutralSOC2             int64 = 97   // SOC2認証
	NeutralCloudEngineer    int64 = 98   // クラウドエンジニア
	NeutralCloudArchitect   int64 = 99   // クラウドアーキテクト
	NeutralTeraReform       int64 = 100  // 寺リフォーム
	NeutralProjectManager   int64 = 101  // プロジェクトマネージャー
	NeutralCloudFunding     int64 = 102  // クラウドファンディング
	NeutralOSSMigration     int64 = 103  // オープンソースマイグレーション
	NeutralDDoSAttack       int64 = 104  // DDoS 攻撃
	NeutralDataBreach       int64 = 105  // データ流出
	NeutralMisconfiguration int64 = 106  // 設定ミス
	NeutralDataScraping     int64 = 107  // データスクレイピング
	NeutralCrawlerBot       int64 = 108  // クローラーボット
	NeutralRegionOutage     int64 = 109  // リージョン障害
	NeutralCryptoMining     int64 = 110  // クリプトマイニング
	NeutralRansomware       int64 = 111  // ランサムウェア
	NeutralComplianceAudit  int64 = 112  // コンプライアンス監査
	NeutralRateLimit        int64 = 113  // レートリミット
	NeutralFailover         int64 = 115  // フェイルオーバー
	NeutralChaosEngineering int64 = 117  // カオスエンジニアリング
	NeutralDBSnapshot       int64 = 119  // DB スナップショット
	NeutralVentureCapital   int64 = 120  // ベンチャーキャピタル
	NeutralWeatherAnomaly   int64 = 122  // 気象異変
	NeutralTenkiUpdate      int64 = 123  // 天気使いの更新
	NeutralITStrategist     int64 = 126  // ITストラテジスト
	NeutralOnpremLinux      int64 = 127  // リラックスペンギン
	NeutralOnpremElephantDB int64 = 128  // エレファントDB
	NeutralOnpremTenki      int64 = 129  // 天気使いサーバー
	NeutralOnpremTunersDB   int64 = 130  // 調律部 DB
	NeutralThrottling       int64 = 135  // スロットリング
)

// CardNames maps card number to card name.
var CardNames = map[int64]string{
	1: "えくぼ",
	3: "アリゲーテナ",
	4: "クジラの統率者<クジランティス>",
	5: "ラフメイカー",
	6: "むらた",
	7: "アデリース",
	8: "オオロバ",
	9: "えりり",
	10: "ダイノ",
	11: "メリーモ",
	12: "SHE Pipeline",
	13: "SHE Front",
	14: "SHE Guard",
	15: "SHE Firewall",
	16: "SHE Queue",
	17: "SHE Gateway",
	18: "SHE Keys",
	19: "SHE Formation",
	20: "SHE Marketplace",
	21: "SHE 料金見積もり",
	22: "Smile Recovery",
	23: "ソラ",
	24: "アサギリ",
	25: "コウテン",
	26: "空即蒼色",
	27: "智の解放者<オープナー>",
	28: "ライ",
	29: "シグレ",
	30: "ハヤテ",
	31: "フブキ",
	32: "百花の天穹<コスモ>",
	33: "シュウウ",
	34: "天気使い DevOps",
	35: "天気使い CDN",
	36: "天気使い ファンネル",
	37: "天気使い Protection",
	38: "天気使い Backup",
	39: "天気使い 空の入口",
	40: "天気使い Vault",
	41: "天気使い Recovery",
	42: "天気使い Template",
	43: "天気使い Migration",
	44: "天気使い Policy",
	45: "天気使い お守り傘",
	46: "天気使い Traffic",
	47: "コンピエッタ",
	48: "スポンジット",
	49: "クラン",
	50: "クーヘンバウムティス",
	51: "バター君",
	52: "Dr. テンソルベ",
	53: "クラン",
	54: "エクレアーエル",
	55: "スーパーバナナ",
	56: "シュトレーンジ",
	57: "トーストア",
	58: "アイスクエリム",
	59: "しゅがーらぼ Build",
	60: "しゅがーらぼ CDN",
	61: "しゅがーらぼ アイスクエリム Analytics",
	62: "しゅがーらぼ Profiler",
	63: "しゅがーらぼ ぱくぱくサブレ",
	64: "しゅがーらぼ だんごフロー",
	65: "しゅがーらぼ Deployment",
	66: "しゅがーらぼ バター君 Batch",
	67: "しゅがーらぼ Knowledge",
	68: "しゅがーらぼ Error Budget",
	70: "コンタータ",
	72: "ベル太",
	73: "テナ",
	74: "コンダクティス",
	75: "ファンファーレクション",
	76: "アピエッタ",
	77: "音の魔術師〈マジシャン・オブ・ミュージック〉",
	78: "エクサノーツ",
	79: "スコアージ",
	81: "カプリッシュ",
	82: "調律部 DevOps",
	83: "調律部 Guard",
	84: "調律部 WAF",
	85: "調律部 ノーツガード",
	86: "調律部 リアル・アンサンブル・クラスター",
	89: "調律部 License",
	90: "調律部 Failback",
	91: "ロードバランサー",
	92: "オートスケーラー",
	93: "プライベートサブネット",
	94: "マルチ AZ",
	96: "ISMS認証",
	97: "SOC2認証",
	98: "クラウドエンジニア",
	99: "クラウドアーキテクト",
	100: "寺リフォーム",
	101: "プロジェクトマネージャー",
	102: "クラウドファンディング",
	103: "オープンソースマイグレーション",
	104: "DDoS 攻撃",
	105: "データ流出",
	106: "設定ミス",
	107: "データスクレイピング",
	108: "クローラーボット",
	109: "リージョン障害",
	110: "クリプトマイニング",
	111: "ランサムウェア",
	112: "コンプライアンス監査",
	113: "レートリミット",
	115: "フェイルオーバー",
	117: "カオスエンジニアリング",
	118: "SHE Ecosystem",
	119: "DB スナップショット",
	120: "ベンチャーキャピタル",
	121: "SHE Smile Horizon Express",
	122: "気象異変",
	123: "天気使いの更新",
	124: "だっくん",
	125: "メレンゲスト",
	126: "ITストラテジスト",
	127: "リラックスペンギン",
	128: "エレファントDB",
	129: "天気使いサーバー",
	130: "調律部 DB",
	131: "SHE Block Storage",
	132: "天気使い ブロックストレージ",
	133: "しゅがーらぼ ブロックストレージ",
	134: "調律部 Block Volume",
	135: "スロットリング",
}
