// Package cardno provides generated card number constants for the Overload Party card game.
//
// All constants and maps in this package are generated by scripts/generate_from_yaml.py
// from the YAML card definitions in data/cards/.
//
// To regenerate: make generate
//
//go:generate python3 ../../scripts/generate_from_yaml.py
package cardno
