// Code generated by scripts/generate_constants.py; DO NOT EDIT.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace OverloadParty.GameData;

/// <summary>BattleDeckCard is a single card entry in a deck snapshot sent to the battle server.</summary>
public class BattleDeckCard
{
    [JsonPropertyName("card_id")]
    public string CardID { get; init; } = "";
    [JsonPropertyName("art_no")]
    public long ArtNo { get; init; }
}

/// <summary>GameCreatedResult is returned when a new game (NPC or PvP) is created on the battle server.</summary>
public class GameCreatedResult
{
    [JsonPropertyName("game_id")]
    public string GameID { get; init; } = "";
    [JsonPropertyName("player1_id")]
    public string Player1ID { get; init; } = "";
    [JsonPropertyName("player2_id")]
    public string Player2ID { get; init; } = "";
    [JsonPropertyName("npc1_model")]
    public string? Npc1Model { get; init; }
    [JsonPropertyName("npc2_model")]
    public string? Npc2Model { get; init; }
}

/// <summary>ActionEvent is a single game event emitted by the battle server after an action.</summary>
public class ActionEvent
{
    [JsonPropertyName("sequence")]
    public long Sequence { get; init; }
    [JsonPropertyName("event_type")]
    public string EventType { get; init; } = "";
    [JsonPropertyName("player_id")]
    public string PlayerID { get; init; } = "";
    [JsonPropertyName("is_system")]
    public bool IsSystem { get; init; }
    [JsonPropertyName("event_data")]
    public JsonElement EventData { get; init; }
    [JsonPropertyName("state")]
    public JsonElement State { get; init; }
}

/// <summary>ActionResult is returned after a game action is processed by the battle server.</summary>
public class ActionResult
{
    [JsonPropertyName("game_over")]
    public bool GameOver { get; init; }
    [JsonPropertyName("winner_num")]
    public long WinnerNum { get; init; }
    [JsonPropertyName("win_reason")]
    public string WinReason { get; init; } = "";
    [JsonPropertyName("npc_pending")]
    public bool NpcPending { get; init; }
    [JsonPropertyName("events")]
    public List<ActionEvent> Events { get; init; } = [];
}

/// <summary>NpcBattleRequest is the request body for POST /api/v1/games/npc.</summary>
public record NpcBattleRequest(
    [property: JsonPropertyName("player_id")] string PlayerID,
    [property: JsonPropertyName("deck_id")] long DeckID,
    [property: JsonPropertyName("cards")] List<BattleDeckCard> Cards,
    [property: JsonPropertyName("npc_model")] string NpcModel);

/// <summary>PvpBattleRequest is the request body for POST /api/v1/games/pvp.</summary>
public record PvpBattleRequest(
    [property: JsonPropertyName("player1_id")] string Player1ID,
    [property: JsonPropertyName("player1_deck_id")] long Player1DeckID,
    [property: JsonPropertyName("player1_cards")] List<BattleDeckCard> Player1Cards,
    [property: JsonPropertyName("player2_id")] string Player2ID,
    [property: JsonPropertyName("player2_deck_id")] long Player2DeckID,
    [property: JsonPropertyName("player2_cards")] List<BattleDeckCard> Player2Cards);

/// <summary>GameActionRequest is the request body for POST /api/v1/games/{gameId}/action.</summary>
public record GameActionRequest(
    [property: JsonPropertyName("player_id")] string PlayerID,
    [property: JsonPropertyName("action_type")] string ActionType,
    [property: JsonPropertyName("data")] JsonElement Data);

/// <summary>NpcAdvanceRequest is the request body for POST /api/v1/games/{gameId}/npc-advance.</summary>
public record NpcAdvanceRequest(
    [property: JsonPropertyName("player_id")] string PlayerID);

