// Code generated by scripts/generate_constants.py; DO NOT EDIT.

namespace OverloadParty.GameData;

/// <summary>Marker interface for all EventData records. Used to constrain GameEvent.EventData type.</summary>
public interface IEventData { }

public class PlayCardEventData : IEventData
{
    public required string CardId { get; init; } = "";
    public required string Zone { get; init; } = "";
    public required int Index { get; init; }
    public bool? Cancelled { get; init; }
}

public class AttachCardEventData : IEventData
{
    public required string CardId { get; init; } = "";
    public required string TargetId { get; init; } = "";
}

public class AttackEventData : IEventData
{
    public required string AttackerId { get; init; } = "";
    public required string TargetId { get; init; } = "";
    public required long Damage { get; init; }
    public required bool Destroyed { get; init; }
    public long? SlaPenalty { get; init; }
    public bool? Cancelled { get; init; }
}

public class ScaleUpEventData : IEventData
{
    public required string InstanceId { get; init; } = "";
    public required string TargetRank { get; init; } = "";
    public string? InstanceFamily { get; init; }
}

public class MonetizeEventData : IEventData
{
    public required long TotalAmount { get; init; }
}

public class DiscardHandEventData : IEventData
{
    public required int DiscardedCount { get; init; }
    public required List<string> DiscardedIds { get; init; } = [];
}

public class UseEffectEventData : IEventData
{
    public required string CardId { get; init; } = "";
    public required string SourceId { get; init; } = "";
    public string? TargetId { get; init; }
}

public class PhaseChangeEventData : IEventData
{
    public required string PreviousPhase { get; init; } = "";
    public required string CurrentPhase { get; init; } = "";
}

public class PhaseEndEventData : IEventData
{
    public required string Phase { get; init; } = "";
    public required bool NeedsDiscard { get; init; }
}

public class TurnEndEventData : IEventData
{
    public required string Phase { get; init; } = "";
    public required long NextTurn { get; init; }
    public required long ActivePlayer { get; init; }
    public required string CurrentPhase { get; init; } = "";
}

public class BattleStartEventData : IEventData
{
    public required string MatchType { get; init; } = "";
    public required string MyName { get; init; } = "";
    public required long MyLevel { get; init; }
    public required string OpponentName { get; init; } = "";
    public required long OpponentLevel { get; init; }
}

public class TurnStartEventData : IEventData
{
    public required long Turn { get; init; }
    public required bool IsMyTurn { get; init; }
}

public class ReactiveRevealedEventData : IEventData
{
    public required string InstanceId { get; init; } = "";
    public required string CardId { get; init; } = "";
}

public class SelectSlotEventData : IEventData
{
    public required string CardId { get; init; } = "";
    public required string InstanceId { get; init; } = "";
    public required string Zone { get; init; } = "";
    public required int Index { get; init; }
}

public class GameOverEventData : IEventData
{
    public required long WinnerNum { get; init; }
    public required string WinReason { get; init; } = "";
}

