// Code generated by scripts/generate_constants.py; DO NOT EDIT.

namespace OverloadParty.GameData;

public class PlayCardEventData
{
    public required string Cardid { get; init; } = "";
    public required string Zone { get; init; } = "";
    public required int Index { get; init; }
    public bool? Cancelled { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["cardId"] = Cardid,
            ["zone"] = Zone,
            ["index"] = Index,
        };
        if (Cancelled is not null) d["cancelled"] = Cancelled;
        return d;
    }
}

public class AttachCardEventData
{
    public required string Cardid { get; init; } = "";
    public required string Targetid { get; init; } = "";

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["cardId"] = Cardid,
            ["targetId"] = Targetid,
        };
        return d;
    }
}

public class AttackEventData
{
    public required string Attackerid { get; init; } = "";
    public required string Targetid { get; init; } = "";
    public required long Damage { get; init; }
    public required bool Destroyed { get; init; }
    public long? Slapenalty { get; init; }
    public bool? Cancelled { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["attackerId"] = Attackerid,
            ["targetId"] = Targetid,
            ["damage"] = Damage,
            ["destroyed"] = Destroyed,
        };
        if (Slapenalty is not null) d["slaPenalty"] = Slapenalty;
        if (Cancelled is not null) d["cancelled"] = Cancelled;
        return d;
    }
}

public class ScaleUpEventData
{
    public required string Instanceid { get; init; } = "";
    public required string Targetrank { get; init; } = "";
    public string? Instancefamily { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["instanceId"] = Instanceid,
            ["targetRank"] = Targetrank,
        };
        if (Instancefamily is not null) d["instanceFamily"] = Instancefamily;
        return d;
    }
}

public class MonetizeEventData
{
    public required long Totalamount { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["totalAmount"] = Totalamount,
        };
        return d;
    }
}

public class DiscardHandEventData
{
    public required int Discardedcount { get; init; }
    public required List<string> Discardedids { get; init; } = [];

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["discardedCount"] = Discardedcount,
            ["discardedIds"] = Discardedids,
        };
        return d;
    }
}

public class UseEffectEventData
{
    public required string Cardid { get; init; } = "";
    public required string Sourceid { get; init; } = "";
    public string? Targetid { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["cardId"] = Cardid,
            ["sourceId"] = Sourceid,
        };
        if (Targetid is not null) d["targetId"] = Targetid;
        return d;
    }
}

public class PhaseChangeEventData
{
    public required string Previousphase { get; init; } = "";
    public required string Currentphase { get; init; } = "";

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["previousPhase"] = Previousphase,
            ["currentPhase"] = Currentphase,
        };
        return d;
    }
}

public class PhaseEndEventData
{
    public required string Phase { get; init; } = "";
    public required bool Needsdiscard { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["phase"] = Phase,
            ["needsDiscard"] = Needsdiscard,
        };
        return d;
    }
}

public class TurnEndEventData
{
    public required string Phase { get; init; } = "";
    public required long Nextturn { get; init; }
    public required long Activeplayer { get; init; }
    public required string Currentphase { get; init; } = "";

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["phase"] = Phase,
            ["nextTurn"] = Nextturn,
            ["activePlayer"] = Activeplayer,
            ["currentPhase"] = Currentphase,
        };
        return d;
    }
}

public class BattleStartEventData
{
    public required string MatchType { get; init; } = "";
    public required string MyName { get; init; } = "";
    public required long MyLevel { get; init; }
    public required string OpponentName { get; init; } = "";
    public required long OpponentLevel { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["match_type"] = MatchType,
            ["my_name"] = MyName,
            ["my_level"] = MyLevel,
            ["opponent_name"] = OpponentName,
            ["opponent_level"] = OpponentLevel,
        };
        return d;
    }
}

public class TurnStartEventData
{
    public required long Turn { get; init; }
    public required bool IsMyTurn { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["turn"] = Turn,
            ["is_my_turn"] = IsMyTurn,
        };
        return d;
    }
}

public class ReactiveRevealedEventData
{
    public required string Instanceid { get; init; } = "";
    public required string Cardid { get; init; } = "";

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["instanceId"] = Instanceid,
            ["cardId"] = Cardid,
        };
        return d;
    }
}

public class GameOverEventData
{
    public required long Winnernum { get; init; }
    public required string Winreason { get; init; } = "";

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["winnerNum"] = Winnernum,
            ["winReason"] = Winreason,
        };
        return d;
    }
}

