// Code generated by scripts/generate_constants.py; DO NOT EDIT.

namespace OverloadParty.GameData.Shop;

public static class ProductTypes
{
    public const string FactionSet = "faction_set";
    public const string Cosmetic = "cosmetic";
    public const string Subscription = "subscription";
}

