"""runner.generate のエンドツーエンドテスト.

asyncapi.yaml ファイルを読み Go 出力ファイルが期待した構造を持つことを検証する。
"""

from __future__ import annotations

from pathlib import Path

from asyncapi_codegen_tools.runner import generate


SAMPLE_SPEC = """\
asyncapi: 3.0.0
info:
  title: sample
  version: 0.1.0
channels:
  Foo:
    address: foo
operations:
  publishFoo:
    action: send
    channel:
      $ref: "#/channels/Foo"
components:
  schemas:
    FooEvent:
      type: object
      description: foo の業務事実。
      required: [event_type, event_id, timestamp, player_id]
      properties:
        event_type:
          type: string
          const: foo_event
        event_id:
          type: string
        timestamp:
          type: string
          format: date-time
        player_id:
          type: string
        optional_count:
          type: integer
"""


class Testasyncapiスペックからのコード生成:
    def test_整形されたGoファイルを生成する(self, tmp_path: Path) -> None:
        spec_path = tmp_path / "asyncapi.yaml"
        spec_path.write_text(SAMPLE_SPEC)
        out_path = tmp_path / "asyncapi_gen.go"

        generate(spec_path=spec_path, output_path=out_path, package="apifoo")

        body = out_path.read_text()

        assert body.startswith("// Code generated by asyncapi-codegen-tools")
        assert "package apifoo" in body
        # date-time フィールドから time の import が自動解決される
        assert '"time"' in body
        assert 'EventTypeFoo = "foo_event"' in body
        # godoc 規約に合わせて struct コメントは型名で始まる
        assert "// FooEvent は foo の業務事実。" in body
        assert "type FooEvent struct {" in body
        # required は値型, optional は pointer + omitempty (フィールド整列のための padding は許容)
        assert 'EventType ' in body and '`json:"event_type"`' in body
        assert 'EventID ' in body and '`json:"event_id"`' in body
        assert 'Timestamp ' in body and 'time.Time' in body and '`json:"timestamp"`' in body
        assert 'PlayerID ' in body and '`json:"player_id"`' in body
        assert 'OptionalCount ' in body and '*int64' in body and '`json:"optional_count,omitempty"`' in body

    def test_出力先の親ディレクトリを自動生成する(self, tmp_path: Path) -> None:
        spec_path = tmp_path / "asyncapi.yaml"
        spec_path.write_text(SAMPLE_SPEC)
        out_path = tmp_path / "nested" / "dir" / "asyncapi_gen.go"

        generate(spec_path=spec_path, output_path=out_path, package="apifoo")

        assert out_path.exists()
        assert "package apifoo" in out_path.read_text()
