// Code generated by scripts/generate_constants.py; DO NOT EDIT.

namespace OverloadParty.GameState;

public class ClientGameState
{
    public string GameID { get; init; } = "";
    public long CurrentTurn { get; init; }
    public string CurrentPhase { get; init; } = "";
    public long ActivePlayer { get; init; }
    public bool IsMyTurn { get; init; }
    public DateTime TurnStartedAt { get; init; }
    public required PlayerView MyView { get; init; }
    public required OpponentView OppView { get; init; }
}

public class PlayerView
{
    public long PlayerNum { get; init; }
    public long Budget { get; init; }
    public long InsightPool { get; init; }
    public long TimeBank { get; init; }
    public required Field Field { get; init; }
    public UndeployedCard[] Hand { get; init; } = [];
    public int RepoCount { get; init; }
    public int TrashCount { get; init; }
    public UndeployedCard[] Trash { get; init; } = [];
    public AvailableAction[]? AvailableActions { get; init; }
}

public class OpponentView
{
    public long PlayerNum { get; init; }
    public long Budget { get; init; }
    public long InsightPool { get; init; }
    public long TimeBank { get; init; }
    public required OpponentField Field { get; init; }
    public int HandCount { get; init; }
    public int RepoCount { get; init; }
    public int TrashCount { get; init; }
    public UndeployedCard[] Trash { get; init; } = [];
}

/// <summary>Field represents one player's complete field layout.</summary>
public class Field
{
    public DeployedResource?[] Frontend { get; init; } = [];
    public DeployedResource?[] Backend { get; init; } = [];
    public DeployedSupport?[] Support { get; init; } = [];
}

/// <summary>Opponent's field with reactive cards hidden.</summary>
public class OpponentField
{
    public DeployedResource?[] Frontend { get; init; } = [];
    public DeployedResource?[] Backend { get; init; } = [];
    public HiddenDeployedSupport?[] Support { get; init; } = [];
}

public class DeployedResource
{
    public string InstanceID { get; init; } = "";
    public string CardID { get; init; } = "";
    public long ArtNo { get; init; }
    public string? Rank { get; init; }
    public string? InstanceFamily { get; init; }
    public bool FaceUp { get; init; }
    public long DeployingTurnsLeft { get; init; }
    public long CurrentAV { get; init; }
    public long MaxAV { get; init; }
    public long? CurrentTP { get; init; }
    public long? MaxTP { get; init; }
    public long? CurrentYield { get; init; }
    public long? MaxYield { get; init; }
    public long Damage { get; init; }
    public TemporaryEffect[] TemporaryEffects { get; init; } = [];
    public long MonetizedAmount { get; init; }
    public bool HasAttacked { get; init; }
    public bool EffectUsedThisTurn { get; init; }
    public bool EffectUsedThisGame { get; init; }
    public long DeployedOnTurn { get; init; }
    public long DeployOrder { get; init; }
    public long ElasticBonus { get; init; }
    public long LastAttackTurn { get; init; }
}

public class DeployedSupport
{
    public string InstanceID { get; init; } = "";
    public string CardID { get; init; } = "";
    public long ArtNo { get; init; }
    public bool FaceUp { get; init; }
    public long DeployingTurnsLeft { get; init; }
    public long DeployOrder { get; init; }
    public bool EffectUsedThisTurn { get; init; }
    public bool EffectUsedThisGame { get; init; }
    public string? TargetInstanceID { get; init; }
}

/// <summary>Support instance with face-down card details hidden.</summary>
public class HiddenDeployedSupport
{
    public string InstanceID { get; init; } = "";
    public string? CardID { get; init; }
    public long ArtNo { get; init; }
    public bool FaceDown { get; init; }
    public bool Peeked { get; init; }
}

public class UndeployedCard
{
    public string InstanceID { get; init; } = "";
    public string CardID { get; init; } = "";
    public long ArtNo { get; init; }
}

public class TemporaryEffect
{
    public string EffectType { get; init; } = "";
    public long Value { get; init; }
    public string Duration { get; init; } = "";
    public string SourceID { get; init; } = "";
    public string Mode { get; init; } = "";
}

public class TurnControlsMessage
{
    public bool CanEndPhase { get; init; }
    public int DiscardRequired { get; init; }
}

