// Code generated by scripts/generate_constants.py; DO NOT EDIT.

export const ZONES = ["frontend", "backend", "support"] as const;
export type Zone = (typeof ZONES)[number];

export const RANKS = ["small", "medium", "large"] as const;
export type Rank = (typeof RANKS)[number];

export const INSTANCE_FAMILIES = ["M", "C", "R"] as const;
export type InstanceFamily = (typeof INSTANCE_FAMILIES)[number] | '';

export const RESTRICTION_VALUES = ["unlimited", "limited", "semi_limited", "forbidden"] as const;
export type Restriction = (typeof RESTRICTION_VALUES)[number];

export const MATCH_TYPES = ["pvp", "npc"] as const;
export type MatchType = (typeof MATCH_TYPES)[number];

export const STAT_TYPES = ["tp", "yield", "av"] as const;
export type StatType = (typeof STAT_TYPES)[number];

export const CARD_TYPES = ["Compute", "DataResource", "Platform", "Attachment", "Strategy", "Reactive", "Incident"] as const;
export type CardType = (typeof CARD_TYPES)[number];

export const COMPUTE_SUBTYPES = ["VM", "Container", "Orchestrator", "Serverless", "AI/ML"] as const;
export type ComputeSubtype = (typeof COMPUTE_SUBTYPES)[number];

export const DATARESOURCE_SUBTYPES = ["Database", "ObjectStorage", "CacheDB"] as const;
export type DataResourceSubtype = (typeof DATARESOURCE_SUBTYPES)[number];

export const FACTIONS = ["Neutral", "SHE", "Tenki", "Sugar", "Tuners"] as const;
export const SELECTABLE_FACTIONS = ["SHE", "Tenki", "Sugar", "Tuners"] as const;
export type FactionId = (typeof SELECTABLE_FACTIONS)[number];

export interface FactionMetadata {
  id: string;
  shortNameJa: string;
  shortNameEn: string;
  fullNameJa: string;
  fullNameEn: string;
  isCollectible: boolean;
  sortOrder: number;
}

export const FACTIONS_METADATA: readonly FactionMetadata[] = [
  {"id": "Neutral", "shortNameJa": "ニュートラル", "shortNameEn": "Neutral", "fullNameJa": "ニュートラル", "fullNameEn": "Neutral", "isCollectible": false, "sortOrder": 0},
  {"id": "SHE", "shortNameJa": "SHE", "shortNameEn": "SHE", "fullNameJa": "SHE（Smile Horizon Express）", "fullNameEn": "SHE (Smile Horizon Express)", "isCollectible": true, "sortOrder": 1},
  {"id": "Tenki", "shortNameJa": "天気使い", "shortNameEn": "Weatherers", "fullNameJa": "天気使い", "fullNameEn": "Weatherers", "isCollectible": true, "sortOrder": 2},
  {"id": "Sugar", "shortNameJa": "しゅがーらぼ", "shortNameEn": "Sugar Lab", "fullNameJa": "しゅがーらぼ", "fullNameEn": "Sugar Lab", "isCollectible": true, "sortOrder": 3},
  {"id": "Tuners", "shortNameJa": "調律部", "shortNameEn": "The Tuners", "fullNameJa": "調律部（チューナーズ）", "fullNameEn": "The Tuners", "isCollectible": true, "sortOrder": 4},
];

export const FACTION_BY_ID: Record<string, FactionMetadata> = {
  "Neutral": FACTIONS_METADATA[0],
  "SHE": FACTIONS_METADATA[1],
  "Tenki": FACTIONS_METADATA[2],
  "Sugar": FACTIONS_METADATA[3],
  "Tuners": FACTIONS_METADATA[4],
};

export const INITIAL_VALUES = {
  deckSize: 30,
} as const;

