// Code generated by scripts/generate_constants.py; DO NOT EDIT.

/** PlayerCardWithDef is a PlayerCard enriched with card definition fields for API responses. */
export interface PlayerCardWithDef {
  card_id: string;
  art_no: number;
  count: number;
  card_name: string;
  faction: string;
  card_type: string;
  resizable: boolean;
  elastic: boolean;
  stats: Record<string, unknown>;
  effect_text?: string;
  restriction: string;
}

/** Deck is the API response for a player's deck with optional card list. */
export interface Deck {
  player_id: string;
  deck_id: number;
  deck_name: string;
  is_valid: boolean;
  playmat_no?: number;
  sleeve_no?: number;
  created_at: string;
  updated_at: string;
  deck_cards?: DeckCard[];
}

/** DeckCard is a single card entry within a deck. */
export interface DeckCard {
  player_id: string;
  deck_id: number;
  card_id: string;
  art_no: number;
  count: number;
}

/** PlayerResponse is the API response for GET /player. */
export interface PlayerResponse {
  player_id: string;
  firebase_uid: string;
  username: string;
  level: number;
  exp: number;
  is_premium: boolean;
  equipped_icon_no?: number;
  selected_faction?: string;
  premium_expires_at?: string;
  created_at: string;
  updated_at: string;
  level_exp_current: number;
  level_exp_required: number;
}

/** BattleLimitResponse is the API response for GET /player/battle-limit. */
export interface BattleLimitResponse {
  daily_battle_count: number;
  daily_battle_limit: number;
  can_battle: boolean;
}

/** UserSettings holds per-player application settings. */
export interface UserSettings {
  player_id: string;
  language: string;
  bgm_volume: number;
  se_volume: number;
  push_enabled: boolean;
  updated_at: string;
}

/** ProductResponse is the API response for a purchasable item in the shop. */
export interface ProductResponse {
  product_id: string;
  name: string;
  type: string;
  price: number;
  content: Record<string, unknown>;
  description?: string;
  image_url?: string;
  is_active: boolean;
  is_owned: boolean;
}

/** EpisodeWithStatus is the API response for a single episode with unlock status. */
export interface EpisodeWithStatus {
  episode_id: string;
  faction: string | null;
  episode_number: number;
  title: string;
  thumbnail_url: string | null;
  is_unlocked: boolean;
  is_completed: boolean;
  lock_reasons: LockReason[];
}

/** LockReason describes a single unmet unlock condition for an episode. */
export interface LockReason {
  type: string;
  required: unknown;
  current?: unknown;
}

/** NewsArticle is the API response for a news article. */
export interface NewsArticle {
  article_id: string;
  source: string;
  title: string;
  summary?: string;
  tags: string[];
  published_at?: string;
  fetched_at: string;
}

/** Announcement represents a single announcement entry. */
export interface Announcement {
  id: string;
  title: string;
  body: string;
  type: string;
  publishedAt: string;
  expiresAt: string;
}

/** DailyTip represents a single daily tip entry. */
export interface DailyTip {
  id: string;
  text: string;
}

/** SpectateGameInfo is the public view of an active game for the spectate list API. */
export interface SpectateGameInfo {
  game_id: string;
  player1_id: string;
  player2_id: string;
  started_at: string;
}

/** DeckCardEntry represents a card entry in a deck create/update request. */
export interface DeckCardEntry {
  card_id: string;
  art_no: number;
  count: number;
}

/** DeckCreateRequest is the request body for POST /decks. */
export interface DeckCreateRequest {
  deck_name: string;
  cards: DeckCardEntry[];
  playmat_no?: number;
  sleeve_no?: number;
}

/** DeckUpdateRequest is the request body for PUT /decks/:id. */
export interface DeckUpdateRequest {
  deck_name: string;
  cards: DeckCardEntry[];
  playmat_no?: number;
  sleeve_no?: number;
}

/** UpdateSettingsRequest is the request body for PUT /player/settings. */
export interface UpdateSettingsRequest {
  language: string;
  bgm_volume: number;
  se_volume: number;
  push_enabled: boolean;
}

/** PurchaseRequest is the request body for POST /shop/purchase. */
export interface PurchaseRequest {
  product_id: string;
  platform: string;
  purchase_token: string;
}

