// Code generated by scripts/generate_constants.py; DO NOT EDIT.

package game_design

// Initial values.
const (
	DeckSize = 30
	InitialBudget = 5000
	InitialInsightPool = 0
	InitialHandSize = 5
)

// Factions.
const (
	FactionNeutral = "Neutral"
	FactionSHE = "SHE"
	FactionTenki = "Tenki"
	FactionSugar = "Sugar"
	FactionTuners = "Tuners"
)

// SelectableFactions is the list of factions players can choose.
var SelectableFactions = []string{
	FactionSHE,
	FactionTenki,
	FactionSugar,
	FactionTuners,
}

// FactionMetadata holds display and ordering information for a faction.
type FactionMetadata struct {
	ID            string
	ShortNameJa   string
	ShortNameEn   string
	FullNameJa    string
	FullNameEn    string
	IsCollectible bool
	SortOrder     int
}

// FactionsMetadata lists all factions in sort order.
var FactionsMetadata = []FactionMetadata{
	{
		ID:            "Neutral",
		ShortNameJa:   "ニュートラル",
		ShortNameEn:   "Neutral",
		FullNameJa:    "ニュートラル",
		FullNameEn:    "Neutral",
		IsCollectible: false,
		SortOrder:     0,
	},
	{
		ID:            "SHE",
		ShortNameJa:   "SHE",
		ShortNameEn:   "SHE",
		FullNameJa:    "SHE（Smile Horizon Express）",
		FullNameEn:    "SHE (Smile Horizon Express)",
		IsCollectible: true,
		SortOrder:     1,
	},
	{
		ID:            "Tenki",
		ShortNameJa:   "天気使い",
		ShortNameEn:   "Weatherers",
		FullNameJa:    "天気使い",
		FullNameEn:    "Weatherers",
		IsCollectible: true,
		SortOrder:     2,
	},
	{
		ID:            "Sugar",
		ShortNameJa:   "しゅがーらぼ",
		ShortNameEn:   "Sugar Lab",
		FullNameJa:    "しゅがーらぼ",
		FullNameEn:    "Sugar Lab",
		IsCollectible: true,
		SortOrder:     3,
	},
	{
		ID:            "Tuners",
		ShortNameJa:   "調律部",
		ShortNameEn:   "The Tuners",
		FullNameJa:    "調律部（チューナーズ）",
		FullNameEn:    "The Tuners",
		IsCollectible: true,
		SortOrder:     4,
	},
}

// FactionByID looks up faction metadata by ID.
var FactionByID = map[string]FactionMetadata{
	"Neutral": FactionsMetadata[0],
	"SHE": FactionsMetadata[1],
	"Tenki": FactionsMetadata[2],
	"Sugar": FactionsMetadata[3],
	"Tuners": FactionsMetadata[4],
}

// Zones.
const (
	ZoneFrontend = "frontend"
	ZoneBackend = "backend"
	ZoneSupport = "support"
)

// Ranks.
const (
	RankSmall = "small"
	RankMedium = "medium"
	RankLarge = "large"
)

// Instance families.
const (
	InstanceFamilyM = "M"
	InstanceFamilyC = "C"
	InstanceFamilyR = "R"
)

// Restriction values.
const (
	RestrictionUnlimited = "unlimited"
	RestrictionLimited = "limited"
	RestrictionSemiLimited = "semi_limited"
	RestrictionForbidden = "forbidden"
)

// Match types.
const (
	MatchTypePvp = "pvp"
	MatchTypeNpc = "npc"
)

// Stat types.
const (
	StatTypeTp = "tp"
	StatTypeYield = "yield"
	StatTypeAv = "av"
)

// Card types.
const (
	CardTypeCompute = "Compute"
	CardTypeDataResource = "DataResource"
	CardTypePlatform = "Platform"
	CardTypeAttachment = "Attachment"
	CardTypeStrategy = "Strategy"
	CardTypeReactive = "Reactive"
	CardTypeIncident = "Incident"
)

// Card subtypes (Compute).
const (
	SubtypeComputeVM = "VM"
	SubtypeComputeContainer = "Container"
	SubtypeComputeOrchestrator = "Orchestrator"
	SubtypeComputeServerless = "Serverless"
	SubtypeComputeAIML = "AI/ML"
)

// Card subtypes (DataResource).
const (
	SubtypeDataResourceDatabase = "Database"
	SubtypeDataResourceObjectStorage = "ObjectStorage"
	SubtypeDataResourceCacheDB = "CacheDB"
)

// RestrictionCopyCount returns the deck investment cap per restriction value.
var RestrictionCopyCount = map[string]int{
	RestrictionUnlimited: 3,
	RestrictionLimited: 1,
	RestrictionSemiLimited: 2,
	RestrictionForbidden: 0,
}

// Game rules.
const (
	GameRuleHandLimit = 6
	GameRuleSlotsPerZone = 3
	GameRuleMaxTurns = 30
	GameRuleLaunchFailureTurn = 3
	GameRuleMaxAttachmentsPerResource = 2
)

// RankMultipliers maps rank to its stat multiplier.
var RankMultipliers = map[string]int{
	RankSmall: 1,
	RankMedium: 2,
	RankLarge: 3,
}

// FamilyMultiplier holds the stat and availability multipliers for an instance family.
type FamilyMultiplier struct {
	Stat float64
	Av   float64
}

// FamilyMultipliers maps instance family to its multipliers.
var FamilyMultipliers = map[string]FamilyMultiplier{
	InstanceFamilyM: {Stat: 1.0, Av: 1.0},
	InstanceFamilyC: {Stat: 1.3, Av: 0.7},
	InstanceFamilyR: {Stat: 0.7, Av: 1.3},
}

