// Code generated by scripts/generate_constants.py; DO NOT EDIT.

package shop

// Product types.
const (
	ProductTypeFactionSet = "faction_set"
	ProductTypeCosmetic = "cosmetic"
	ProductTypeSubscription = "subscription"
)

