// Code generated by scripts/generate_constants.py; DO NOT EDIT.

namespace OverloadParty.GameData.Newsfeed;

public static class CloudNewsSources
{
    public const string Aws = "aws";
    public const string GoogleCloud = "google-cloud";
    public const string Azure = "azure";
    public const string Oci = "oci";
    public const string Other = "other";
}

