// Code generated by scripts/generate_constants.py; DO NOT EDIT.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace OverloadParty.ApiBattleRpc;

/// <summary>BattleDeckCard is a single card entry in a deck snapshot sent to the battle server.</summary>
public class BattleDeckCard
{
    [JsonPropertyName("card_id")]
    public string CardID { get; init; } = "";
    [JsonPropertyName("art_no")]
    public long ArtNo { get; init; }
}

/// <summary>GameCreatedResult is returned when a new game (NPC or PvP) is created on the battle server.</summary>
public class GameCreatedResult
{
    [JsonPropertyName("game_id")]
    public string GameID { get; init; } = "";
}

/// <summary>ActionEvent is a single game event emitted by the battle server after an action.</summary>
public class ActionEvent
{
    [JsonPropertyName("sequence")]
    public long Sequence { get; init; }
    [JsonPropertyName("event_type")]
    public string EventType { get; init; } = "";
    [JsonPropertyName("player_num")]
    public long? PlayerNum { get; init; }
    [JsonPropertyName("event_data")]
    public JsonElement EventData { get; init; }
    [JsonPropertyName("state")]
    public JsonElement State { get; init; }
}

/// <summary>ActionResult is returned after a game action is processed by the battle server.</summary>
public class ActionResult
{
    [JsonPropertyName("game_over")]
    public bool GameOver { get; init; }
    [JsonPropertyName("winning_player_num")]
    public long WinningPlayerNum { get; init; }
    [JsonPropertyName("win_reason")]
    public string WinReason { get; init; } = "";
    [JsonPropertyName("npc_pending")]
    public bool NpcPending { get; init; }
    [JsonPropertyName("events")]
    public List<ActionEvent> Events { get; init; } = [];
}

/// <summary>NpcBattleRequest is the request body for POST /api/v1/games/npc.</summary>
public record NpcBattleRequest(
    [property: JsonPropertyName("deck_cards")] List<BattleDeckCard> DeckCards,
    [property: JsonPropertyName("npc_model")] string NpcModel);

/// <summary>PvpBattleRequest is the request body for POST /api/v1/games/pvp.</summary>
public record PvpBattleRequest(
    [property: JsonPropertyName("deck1_cards")] List<BattleDeckCard> Deck1Cards,
    [property: JsonPropertyName("deck2_cards")] List<BattleDeckCard> Deck2Cards);

/// <summary>GameActionRequest is the request body for POST /api/v1/games/{gameId}/actions.</summary>
public record GameActionRequest(
    [property: JsonPropertyName("player_num")] long PlayerNum,
    [property: JsonPropertyName("action_type")] string ActionType,
    [property: JsonPropertyName("data")] JsonElement Data);

