// Code generated by generate_from_yaml.py from data/event_schemas.json; DO NOT EDIT.

namespace OverloadParty.GameData;

public class PlayCardEventData
{
    public required long CardId { get; init; }
    public required string Zone { get; init; } = "";
    public required int Index { get; init; }
    public bool? Cancelled { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["cardId"] = CardId,
            ["zone"] = Zone,
            ["index"] = Index,
        };
        if (Cancelled is not null) d["cancelled"] = Cancelled;
        return d;
    }
}

public class AttachCardEventData
{
    public required long CardId { get; init; }
    public required string TargetId { get; init; } = "";

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["cardId"] = CardId,
            ["targetId"] = TargetId,
        };
        return d;
    }
}

public class AttackEventData
{
    public required string AttackerId { get; init; } = "";
    public required string TargetId { get; init; } = "";
    public required long Damage { get; init; }
    public required bool Destroyed { get; init; }
    public long? SlaPenalty { get; init; }
    public bool? Cancelled { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["attackerId"] = AttackerId,
            ["targetId"] = TargetId,
            ["damage"] = Damage,
            ["destroyed"] = Destroyed,
        };
        if (SlaPenalty is not null) d["slaPenalty"] = SlaPenalty;
        if (Cancelled is not null) d["cancelled"] = Cancelled;
        return d;
    }
}

public class ScaleUpEventData
{
    public required string InstanceId { get; init; } = "";
    public required string TargetRank { get; init; } = "";
    public string? InstanceFamily { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["instanceId"] = InstanceId,
            ["targetRank"] = TargetRank,
        };
        if (InstanceFamily is not null) d["instanceFamily"] = InstanceFamily;
        return d;
    }
}

public class MonetizeEventData
{
    public required long TotalAmount { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["totalAmount"] = TotalAmount,
        };
        return d;
    }
}

public class DiscardHandEventData
{
    public required int DiscardedCount { get; init; }
    public required List<string> DiscardedIds { get; init; } = [];

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["discardedCount"] = DiscardedCount,
            ["discardedIds"] = DiscardedIds,
        };
        return d;
    }
}

public class ActivateEffectEventData
{
    public required long CardNo { get; init; }
    public required string SourceId { get; init; } = "";
    public string? TargetId { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["cardNo"] = CardNo,
            ["sourceId"] = SourceId,
        };
        if (TargetId is not null) d["targetId"] = TargetId;
        return d;
    }
}

public class MigrateEventData
{
    public required string SourceInstanceId { get; init; } = "";
    public required string TargetInstanceId { get; init; } = "";
    public required long SourceCardId { get; init; }
    public required long TargetCardId { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["sourceInstanceId"] = SourceInstanceId,
            ["targetInstanceId"] = TargetInstanceId,
            ["sourceCardId"] = SourceCardId,
            ["targetCardId"] = TargetCardId,
        };
        return d;
    }
}

public class PhaseChangeEventData
{
    public required string PreviousPhase { get; init; } = "";
    public required string CurrentPhase { get; init; } = "";

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["previousPhase"] = PreviousPhase,
            ["currentPhase"] = CurrentPhase,
        };
        return d;
    }
}

public class PhaseEndEventData
{
    public required string Phase { get; init; } = "";
    public required bool NeedsDiscard { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["phase"] = Phase,
            ["needsDiscard"] = NeedsDiscard,
        };
        return d;
    }
}

public class TurnEndEventData
{
    public required string Phase { get; init; } = "";
    public required long NextTurn { get; init; }
    public required long ActivePlayer { get; init; }
    public required string CurrentPhase { get; init; } = "";

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["phase"] = Phase,
            ["nextTurn"] = NextTurn,
            ["activePlayer"] = ActivePlayer,
            ["currentPhase"] = CurrentPhase,
        };
        return d;
    }
}

public class TurnStartEventData
{
    public required long Turn { get; init; }
    public required long ActivePlayer { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["turn"] = Turn,
            ["activePlayer"] = ActivePlayer,
        };
        return d;
    }
}

public class ReactiveRevealedEventData
{
    public required string InstanceId { get; init; } = "";
    public required long CardId { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["instanceId"] = InstanceId,
            ["cardId"] = CardId,
        };
        return d;
    }
}

public class MigrationCompleteEventData
{
    public required string SourceInstanceId { get; init; } = "";
    public required string TargetInstanceId { get; init; } = "";
    public required long SourceCardId { get; init; }
    public required long TargetCardId { get; init; }

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["sourceInstanceId"] = SourceInstanceId,
            ["targetInstanceId"] = TargetInstanceId,
            ["sourceCardId"] = SourceCardId,
            ["targetCardId"] = TargetCardId,
        };
        return d;
    }
}

public class GameOverEventData
{
    public required long WinnerNum { get; init; }
    public required string WinReason { get; init; } = "";

    public Dictionary<string, object> ToDictionary()
    {
        var d = new Dictionary<string, object>
        {
            ["winnerNum"] = WinnerNum,
            ["winReason"] = WinReason,
        };
        return d;
    }
}

