// Code generated by scripts/generate_constants.py; DO NOT EDIT.

namespace OverloadParty.GameData;

public static class GameConstants
{
    // Initial values
    public const int DeckSize = 30;

    // Factions
    public const string FactionSHE = "SHE";
    public const string FactionTenki = "Tenki";
    public const string FactionSugar = "Sugar";
    public const string FactionTuners = "Tuners";
    public const string FactionNeutral = "Neutral";

    // Zones (wire format)
    public const string ZoneFrontend = "frontend";
    public const string ZoneBackend = "backend";
    public const string ZoneSupport = "support";
}

