// Code generated by generate_from_yaml.py from data/constants.json; DO NOT EDIT.

namespace OverloadParty.Generated;

public static class GameConstants
{
    // Initial values
    public const long InitialBudget = 5000;
    public const long InitialInsightPool = 0;
    public const int InitialHandSize = 5;
    public const int HandLimit = 6;
    public const long InitialTimeBank = 480;
    public const int DeckSize = 30;
    public const int MaxAttachments = 2;
    public const int SlotsPerZone = 3;

    // Factions
    public const string FactionSHE = "SHE";
    public const string FactionTenki = "Tenki";
    public const string FactionSugar = "Sugar";
    public const string FactionTuners = "Tuners";
    public const string FactionNeutral = "Neutral";

    // Zones (wire format)
    public const string ZoneFrontend = "frontend";
    public const string ZoneBackend = "backend";
    public const string ZoneSupport = "support";
}

