// Code generated by scripts/generate_constants.py; DO NOT EDIT.

namespace OverloadParty.GameData;

/// <summary>Available action that a player can perform during their turn.</summary>
public class AvailableAction
{
    public required string Type { get; init; } = "";
    public string? HandInstanceId { get; init; }
    public string? CardId { get; init; }
    public List<string>? ValidZones { get; init; }
    public List<string>? ValidTargets { get; init; }
    public int? Cost { get; init; }
    public List<string>? ChoiceOptions { get; init; }
    public string? SourceInstanceId { get; init; }
    public string? TargetRank { get; init; }
    public string? InstanceFamily { get; init; }
    public bool? NeedsFamily { get; init; }
    public long? RemainingCapacity { get; init; }
    public string? EffectTargetType { get; init; }
    public int? RequiredCount { get; init; }
}

