"""asyncapi-codegen-tools のエントリポイント.

`generate` をライブラリ呼び出しとして使い、`cli` は `python -m asyncapi_codegen_tools` /
`asyncapi-codegen` console script の入口。
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml
from codegen_tools.go_emitter import GoConstStyle, GoStyle, render_go_file

from .parser import parse_spec


def generate(
    *,
    spec_path: Path,
    output_path: Path,
    package: str,
) -> None:
    """spec_path の AsyncAPI YAML を読み、output_path に Go ソースを書き出す."""
    raw: dict[str, Any] = yaml.safe_load(spec_path.read_text())
    parsed = parse_spec(raw)

    style = GoStyle(
        header=f"// Code generated by asyncapi-codegen-tools from {spec_path.name}; DO NOT EDIT.",
        tag_keys=("json",),
        type_comment_multiline=True,
        const_style=GoConstStyle(
            type_annotation=False,
            quote_string_only=True,
        ),
    )

    body = render_go_file(
        package=package,
        types=parsed["types"],
        style=style,
        constants=parsed["constants"],
        emit_tags=("json",),
        trailing_blank_line=True,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(body)


def cli(argv: list[str] | None = None) -> int:
    """CLI 入口. exit code を返す."""
    p = argparse.ArgumentParser(
        prog="asyncapi-codegen",
        description="AsyncAPI 3.0 spec から Go 型を生成する。",
    )
    p.add_argument("--input", "-i", required=True, type=Path, help="入力 asyncapi.yaml")
    p.add_argument("--output", "-o", required=True, type=Path, help="出力 .go ファイル")
    p.add_argument("--package", "-p", required=True, help="出力 Go パッケージ名")
    args = p.parse_args(argv)

    generate(spec_path=args.input, output_path=args.output, package=args.package)
    return 0


if __name__ == "__main__":
    sys.exit(cli())
