// Code generated by scripts/generate_constants.py; DO NOT EDIT.

package newsfeed

// Cloud news sources.
const (
	CloudNewsSourceAws = "aws"
	CloudNewsSourceGoogleCloud = "google-cloud"
	CloudNewsSourceAzure = "azure"
	CloudNewsSourceOci = "oci"
	CloudNewsSourceOther = "other"
)

