// Code generated by scripts/generate_constants.py; DO NOT EDIT.

import type { AvailableAction } from './variantTypes';

export interface CardDefinition {
  card_id: string;
  card_name: string;
  resource_label: string;
  faction: string;
  card_type: string;
  deploy_turns: number;
  resizable: boolean;
  elastic: boolean;
  elastic_increment?: number;
  free_tier?: number;
  cost_per_request?: number;
  stats: Record<string, unknown>;
  effect_text?: string;
  effects?: Record<string, unknown>;
  passive_effects?: PassiveEffect[];
  platform_effects?: PlatformEffect[];
  attachment_effects?: AttachmentEffect[];
  restriction: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

/** ComputeStats for Compute, Container, Orchestrator, Serverless, AI/ML card types. */
export interface ComputeStats {
  throughput: number;
  throughput_max?: number;
  availability: number;
  maintenance_cost: number;
  sla_penalty: number;
}

/** DataStats for Database, ObjectStorage, CacheDB card types. */
export interface DataStats {
  yield: number;
  yield_max?: number;
  availability: number;
  maintenance_cost: number;
  sla_penalty: number;
}

export interface PassiveEffect {
  type: string;
  params: Record<string, unknown>;
}

export interface PlatformEffect {
  type: string;
  params: Record<string, unknown>;
}

export interface AttachmentEffect {
  type: string;
  params: Record<string, unknown>;
}

export interface PassiveEffectConfig {
  faction?: string;
  card_types?: string[];
  bonus_per_card?: number;
  flat_bonus?: number;
  multi_model_card_ids?: string[];
  specific_card_ids?: string[];
  zone?: string;
  exclude_self?: boolean;
}

export interface PlatformEffectConfig {
  target_faction?: string;
  target_card_types?: string[];
  bonus?: number;
  reduction?: number;
  apply_to_self?: boolean;
}

export interface AttachmentEffectConfig {
  stat_type: string;
  bonus: number;
}

export interface ClientGameState {
  gameID: string;
  currentTurn: number;
  currentPhase: string;
  activePlayer: number;
  isMyTurn: boolean;
  turnStartedAt: string;
  myView: PlayerView;
  oppView: OpponentView;
}

export interface PlayerView {
  playerNum: number;
  budget: number;
  insightPool: number;
  timeBank: number;
  field: Field;
  hand: UndeployedCard[];
  repoCount: number;
  trashCount: number;
  trash: UndeployedCard[];
  availableActions?: AvailableAction[];
}

export interface OpponentView {
  playerNum: number;
  budget: number;
  insightPool: number;
  timeBank: number;
  field: OpponentField;
  handCount: number;
  repoCount: number;
  trashCount: number;
  trash: UndeployedCard[];
}

/** Field represents one player's complete field layout. */
export interface Field {
  frontend: (DeployedResource | null)[];
  backend: (DeployedResource | null)[];
  support: (DeployedSupport | null)[];
}

/** Opponent's field with reactive cards hidden. */
export interface OpponentField {
  frontend: (DeployedResource | null)[];
  backend: (DeployedResource | null)[];
  support: (HiddenDeployedSupport | null)[];
}

export interface DeployedResource {
  instanceID: string;
  cardID: string;
  artNo: number;
  rank?: string;
  instanceFamily?: string;
  faceUp: boolean;
  deployingTurnsLeft: number;
  currentAV: number;
  maxAV: number;
  currentTP?: number;
  maxTP?: number;
  currentYield?: number;
  maxYield?: number;
  damage: number;
  temporaryEffects: TemporaryEffect[];
  monetizedAmount: number;
  hasAttacked: boolean;
  effectUsedThisTurn: boolean;
  effectUsedThisGame: boolean;
  deployedOnTurn: number;
  deployOrder: number;
  elasticBonus: number;
  lastAttackTurn: number;
}

export interface DeployedSupport {
  instanceID: string;
  cardID: string;
  artNo: number;
  faceUp: boolean;
  deployingTurnsLeft: number;
  deployOrder: number;
  effectUsedThisTurn: boolean;
  effectUsedThisGame: boolean;
  targetInstanceID?: string;
}

/** Support instance with face-down card details hidden. */
export interface HiddenDeployedSupport {
  instanceID: string;
  cardID?: string;
  artNo: number;
  faceDown: boolean;
  peeked: boolean;
}

export interface UndeployedCard {
  instanceID: string;
  cardID: string;
  artNo: number;
}

export interface TemporaryEffect {
  effectType: string;
  value: number;
  duration: string;
  sourceID: string;
}

