-- Auto-generated by scripts/generate_products.py. DO NOT EDIT.

INSERT INTO products
  (product_id, name, type, price, content, faction_id, description, image_url, is_active)
VALUES
  ('pack-she', 'SHEカードパック', 'faction_set', 480, '{}'::jsonb, 'SHE', 'SHEファクションの全カードが手に入るパック。', '/assets/shop/pack-she.webp', true),
  ('pack-tenki', '天気使いカードパック', 'faction_set', 480, '{}'::jsonb, 'Tenki', '天気使いファクションの全カードが手に入るパック。', '/assets/shop/pack-tenki.webp', true),
  ('pack-sugar', 'しゅがーらぼカードパック', 'faction_set', 480, '{}'::jsonb, 'Sugar', 'しゅがーらぼファクションの全カードが手に入るパック。', '/assets/shop/pack-sugar.webp', true),
  ('pack-tuners', '調律部カードパック', 'faction_set', 480, '{}'::jsonb, 'Tuners', '調律部ファクションの全カードが手に入るパック。', '/assets/shop/pack-tuners.webp', true),
  ('sleeve-a', 'カードスリーブA', 'cosmetic', 300, '{"item_type": "sleeve", "item_no": 1}'::jsonb, NULL, 'シンプルなデザインのカードスリーブ。', '/assets/shop/sleeve-a.webp', true),
  ('sleeve-b', 'カードスリーブB', 'cosmetic', 300, '{"item_type": "sleeve", "item_no": 2}'::jsonb, NULL, 'メタリックなデザインのカードスリーブ。', '/assets/shop/sleeve-b.webp', true),
  ('sleeve-c', 'カードスリーブC', 'cosmetic', 300, '{"item_type": "sleeve", "item_no": 3}'::jsonb, NULL, 'ホログラムデザインのカードスリーブ。', '/assets/shop/sleeve-c.webp', true),
  ('playmat-a', 'プレイマットA', 'cosmetic', 500, '{"item_type": "playmat", "item_no": 1}'::jsonb, NULL, 'クラウドインフラをモチーフにしたプレイマット。', '/assets/shop/playmat-a.webp', true),
  ('playmat-b', 'プレイマットB', 'cosmetic', 500, '{"item_type": "playmat", "item_no": 2}'::jsonb, NULL, 'サーバールームをモチーフにしたプレイマット。', '/assets/shop/playmat-b.webp', true),
  ('playmat-c', 'プレイマットC', 'cosmetic', 500, '{"item_type": "playmat", "item_no": 3}'::jsonb, NULL, 'ネットワーク回路をモチーフにしたプレイマット。', '/assets/shop/playmat-c.webp', true),
  ('stamp-a', 'スタンプセットA', 'cosmetic', 200, '{"item_type": "stamp", "item_no": 1}'::jsonb, NULL, '基本の表情スタンプ8種セット。', '/assets/shop/stamp-a.webp', true),
  ('stamp-b', 'スタンプセットB', 'cosmetic', 200, '{"item_type": "stamp", "item_no": 2}'::jsonb, NULL, 'クラウド用語スタンプ8種セット。', '/assets/shop/stamp-b.webp', true),
  ('premium-pass', 'プレミアムパス', 'subscription', 980, '{"duration_days": 30}'::jsonb, NULL, '30日間のプレミアム特典。デイリーログインボーナス増量＋バトル回数無制限。', '/assets/shop/premium-pass.webp', true)

ON CONFLICT (product_id) DO UPDATE SET
  name        = EXCLUDED.name,
  type        = EXCLUDED.type,
  price       = EXCLUDED.price,
  content     = EXCLUDED.content,
  faction_id  = EXCLUDED.faction_id,
  description = EXCLUDED.description,
  image_url   = EXCLUDED.image_url,
  is_active   = EXCLUDED.is_active;
