// Code generated by scripts/generate_constants.py; DO NOT EDIT.

namespace OverloadParty.GameDesignConstants;

public static class InitialValues
{
    public const int DeckSize = 30;
    public const int InitialBudget = 5000;
    public const int InitialInsightPool = 0;
    public const int InitialHandSize = 5;
}

public static class Factions
{
    public const string Neutral = "Neutral";
    public const string SHE = "SHE";
    public const string Tenki = "Tenki";
    public const string Sugar = "Sugar";
    public const string Tuners = "Tuners";
}

public static class SelectableFactions
{
    public static readonly string[] All = [
        Factions.SHE,
        Factions.Tenki,
        Factions.Sugar,
        Factions.Tuners,
    ];
}

public record FactionMetadata(
    string Id,
    string ShortNameJa,
    string ShortNameEn,
    string FullNameJa,
    string FullNameEn,
    bool IsCollectible,
    int SortOrder
);

public static class FactionsMetadata
{
    public static readonly FactionMetadata[] All = [
        new FactionMetadata("Neutral", "ニュートラル", "Neutral", "ニュートラル", "Neutral", false, 0),
        new FactionMetadata("SHE", "SHE", "SHE", "SHE（Smile Horizon Express）", "SHE (Smile Horizon Express)", true, 1),
        new FactionMetadata("Tenki", "天気使い", "Weatherers", "天気使い", "Weatherers", true, 2),
        new FactionMetadata("Sugar", "しゅがーらぼ", "Sugar Lab", "しゅがーらぼ", "Sugar Lab", true, 3),
        new FactionMetadata("Tuners", "調律部", "The Tuners", "調律部（チューナーズ）", "The Tuners", true, 4),
    ];

    public static readonly System.Collections.Generic.Dictionary<string, FactionMetadata> ById =
        System.Linq.Enumerable.ToDictionary(All, m => m.Id);
}

public static class Zones
{
    public const string Frontend = "frontend";
    public const string Backend = "backend";
    public const string Support = "support";
}

public static class Ranks
{
    public const string Small = "small";
    public const string Medium = "medium";
    public const string Large = "large";
}

public static class InstanceFamilies
{
    public const string M = "M";
    public const string C = "C";
    public const string R = "R";
}

public static class RestrictionValues
{
    public const string Unlimited = "unlimited";
    public const string Limited = "limited";
    public const string SemiLimited = "semi_limited";
    public const string Forbidden = "forbidden";
}

public static class MatchTypes
{
    public const string Pvp = "pvp";
    public const string Npc = "npc";
}

public static class StatTypes
{
    public const string Tp = "tp";
    public const string Yield = "yield";
    public const string Av = "av";
}

public static class CardTypes
{
    public const string Compute = "Compute";
    public const string DataResource = "DataResource";
    public const string Platform = "Platform";
    public const string Attachment = "Attachment";
    public const string Strategy = "Strategy";
    public const string Reactive = "Reactive";
    public const string Incident = "Incident";
}

public static class Subtypes
{
    public static class Compute
    {
        public const string VM = "VM";
        public const string Container = "Container";
        public const string Orchestrator = "Orchestrator";
        public const string Serverless = "Serverless";
        public const string AIML = "AI/ML";
    }

    public static class DataResource
    {
        public const string Database = "Database";
        public const string ObjectStorage = "ObjectStorage";
        public const string CacheDB = "CacheDB";
    }
}

public static class GameRules
{
    public const int HandLimit = 6;
    public const int SlotsPerZone = 3;
    public const int MaxTurns = 30;
    public const int LaunchFailureTurn = 3;
}

public static class RankMultipliers
{
    public const long Small = 1;
    public const long Medium = 2;
    public const long Large = 3;
}

public static class FamilyMultipliers
{
    public const double MStat = 1.0;
    public const double MAv = 1.0;
    public const double CStat = 1.3;
    public const double CAv = 0.7;
    public const double RStat = 0.7;
    public const double RAv = 1.3;
}

