#!/usr/bin/env python3
"""Generate shared constants, event data types, and Go models from YAML definitions.

Outputs:
  - packages/gamedata/constants/constants_gen.go  (Go constants)
  - packages/gamedata/model/*_gen.go              (Go model structs)
  - packages/dotnet/GameConstants_gen.cs           (C# constants)
  - packages/dotnet/EventData_gen.cs               (C# event data types)
  - packages/npm/src/constants.ts                  (TS constants)
  - packages/npm/src/eventData.ts                  (TS event data types)
  - packages/npm/src/wsMessages.ts                 (TS WS message types)

Usage:
    python3 scripts/generate_constants.py
"""

import json
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

# ─── Paths ──────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
CONSTANTS_YAML = ROOT / "data" / "constants.yaml"
EVENT_SCHEMAS_YAML = ROOT / "data" / "event_schemas.yaml"
MODELS_YAML = ROOT / "data" / "models.yaml"

GO_DIR = ROOT / "packages" / "gamedata"
DOTNET_DIR = ROOT / "packages" / "dotnet"
NPM_DIR = ROOT / "packages" / "npm"

# ─── Helpers ────────────────────────────────────────────

_GENERATED_HEADER = "// Code generated by scripts/generate_constants.py; DO NOT EDIT."


def _snake_to_pascal(s):
    return "".join(w.title() for w in s.split("_"))


def _camel_to_pascal(s):
    return s[0].upper() + s[1:]


def _to_pascal(value):
    """Convert a YAML value to a PascalCase identifier.

    Handles snake_case, lowercase, PascalCase, uppercase, and slashes.
    """
    value = value.replace("/", "")
    if "_" in value:
        return "".join(w.title() for w in value.split("_"))
    if value and value[0].isupper():
        return value
    return value.title() if value else value


# Keys that follow the simple pattern: flat list → const block / static class / as-const array.
# (yaml_key, go_prefix, go_comment, cs_class, ts_const, ts_type)
_SIMPLE_LIST_KEYS = [
    ("phases", "Phase", "Phases", "Phases", "PHASES", "GamePhase"),
    ("zones", "Zone", "Zones", "Zones", "ZONES", "Zone"),
    ("ranks", "Rank", "Ranks", "Ranks", "RANKS", "Rank"),
    ("instance_families", "InstanceFamily", "Instance families", "InstanceFamilies", "INSTANCE_FAMILIES", "InstanceFamily"),
    ("game_status", "GameStatus", "Game status", "GameStatus", "GAME_STATUS", "GameStatus"),
    ("win_reasons", "WinReason", "Win reasons", "WinReasons", "WIN_REASONS", "WinReason"),
    ("action_types", "ActionType", "Action types", "ActionTypes", "ACTION_TYPES", "GameActionType"),
    ("event_types", "EventType", "Event types", "EventTypes", "EVENT_TYPES", "EventType"),
    ("effect_durations", "EffectDuration", "Effect durations", "EffectDurations", "EFFECT_DURATIONS", "EffectDuration"),
    ("restriction_values", "Restriction", "Restriction values", "RestrictionValues", "RESTRICTION_VALUES", "Restriction"),
    ("trigger_types", "TriggerType", "Trigger types", "TriggerTypes", "TRIGGER_TYPES", "TriggerType"),
    ("effect_ops", "EffectOp", "Effect operations", "EffectOps", "EFFECT_OPS", "EffectOp"),
    ("buff_types", "BuffType", "Buff types", "BuffTypes", "BUFF_TYPES", "BuffType"),
    ("custom_effects", "CustomEffect", "Custom effects", "CustomEffects", "CUSTOM_EFFECTS", "CustomEffect"),
    ("effect_categories", "EffectCategory", "Effect categories", "EffectCategories", "EFFECT_CATEGORIES", "EffectCategory"),
    ("effect_target_types", "EffectTargetType", "Effect target types", "EffectTargetTypes", "EFFECT_TARGET_TYPES", "EffectTargetType"),
    ("player_refs", "PlayerRef", "Player references", "PlayerRefs", "PLAYER_REFS", "PlayerRef"),
    ("use_limits", "UseLimit", "Use limits", "UseLimits", "USE_LIMITS", "UseLimit"),
    ("match_types", "MatchType", "Match types", "MatchTypes", "MATCH_TYPES", "MatchType"),
    ("stat_types", "StatType", "Stat types", "StatTypes", "STAT_TYPES", "StatType"),
    ("guard_types", "GuardType", "Guard types", "GuardTypes", "GUARD_TYPES", "GuardType"),
    ("selector_pick_modes", "SelectorPickMode", "Selector pick modes", "SelectorPickModes", "SELECTOR_PICK_MODES", "SelectorPickMode"),
]


# ─── Generate Go (constants) ───────────────────────────
def _go_const_block(comment, prefix, values):
    """Generate a Go const block from a list of values."""
    lines = [f"// {comment}."]
    lines.append("const (")
    for v in values:
        name = f"{prefix}{_to_pascal(v)}"
        lines.append(f'\t{name} = "{v}"')
    lines.append(")")
    lines.append("")
    return lines


def generate_go_constants(constants, *, out_path):
    """Generate constants_gen.go for the Go package."""
    go_out = Path(out_path)

    iv = constants["initial_values"]
    lines = [
        _GENERATED_HEADER,
        "",
        "package constants",
        "",
        "// Deck size.",
        "const (",
        f"\tDeckSize = {iv['deck_size']}",
        ")",
        "",
    ]

    # Factions (use value as-is since they're PascalCase/uppercase).
    lines.append("// Factions.")
    lines.append("const (")
    for faction in constants["factions"]:
        lines.append(f'\tFaction{faction} = "{faction}"')
    lines.append(")")
    lines.append("")

    lines.append("// SelectableFactions is the list of factions players can choose.")
    lines.append("var SelectableFactions = []string{")
    for f in constants["selectable_factions"]:
        lines.append(f"\tFaction{f},")
    lines.append("}")
    lines.append("")

    for yaml_key, go_prefix, go_comment, _, _, _ in _SIMPLE_LIST_KEYS:
        values = constants.get(yaml_key)
        if values is None:
            continue
        lines.extend(_go_const_block(go_comment, go_prefix, values))

    # WS message types (nested: server + client share WSMsg prefix).
    ws = constants["ws_message_types"]
    lines.append("// WS server message types.")
    lines.append("const (")
    for v in ws["server"]:
        lines.append(f'\tWSServerMsg{_to_pascal(v)} = "{v}"')
    lines.append(")")
    lines.append("")
    lines.append("// WS client message types.")
    lines.append("const (")
    for v in ws["client"]:
        lines.append(f'\tWSClientMsg{_to_pascal(v)} = "{v}"')
    lines.append(")")
    lines.append("")

    ct = constants["card_types"]
    all_types = ct["compute"] + ct["data"] + ct["support"]
    lines.append("// Card types.")
    lines.append("const (")
    for v in all_types:
        lines.append(f'\tCardType{_to_pascal(v)} = "{v}"')
    lines.append(")")
    lines.append("")

    compute_set = ", ".join(f'CardType{_to_pascal(v)}' for v in ct["compute"])
    data_set = ", ".join(f'CardType{_to_pascal(v)}' for v in ct["data"])
    support_non_attach = [t for t in ct["support"] if t != "Attachment"]
    support_set = ", ".join(f'CardType{_to_pascal(v)}' for v in support_non_attach)

    lines.append("// IsResourceType returns true if the card type is a deployable resource (compute or data).")
    lines.append("func IsResourceType(cardType string) bool {")
    lines.append("\tswitch cardType {")
    lines.append(f"\tcase {compute_set}, {data_set}:")
    lines.append("\t\treturn true")
    lines.append("\t}")
    lines.append("\treturn false")
    lines.append("}")
    lines.append("")

    lines.append("// IsFrontendEligible returns true if the card can be placed in the frontend zone.")
    lines.append("func IsFrontendEligible(cardType string) bool {")
    lines.append("\tswitch cardType {")
    lines.append(f"\tcase {compute_set}, CardTypeObjectStorage:")
    lines.append("\t\treturn true")
    lines.append("\t}")
    lines.append("\treturn false")
    lines.append("}")
    lines.append("")

    lines.append("// IsBackendEligible returns true if the card can be placed in the backend zone.")
    lines.append("func IsBackendEligible(cardType string) bool {")
    lines.append("\tswitch cardType {")
    lines.append(f"\tcase {data_set}, {compute_set}:")
    lines.append("\t\treturn true")
    lines.append("\t}")
    lines.append("\treturn false")
    lines.append("}")
    lines.append("")

    lines.append("// IsSupportType returns true if the card goes in the support zone.")
    lines.append("func IsSupportType(cardType string) bool {")
    lines.append("\tswitch cardType {")
    lines.append(f"\tcase {support_set}:")
    lines.append("\t\treturn true")
    lines.append("\t}")
    lines.append("\treturn false")
    lines.append("}")
    lines.append("")

    lines.append("// IsAttachmentType returns true if the card is an Attachment.")
    lines.append("func IsAttachmentType(cardType string) bool {")
    lines.append("\treturn cardType == CardTypeAttachment")
    lines.append("}")
    lines.append("")

    lines.append("// RestrictionCopyCount returns the maximum number of copies allowed in a deck.")
    lines.append("func RestrictionCopyCount(restriction string) int {")
    lines.append("\tswitch restriction {")
    lines.append("\tcase RestrictionForbidden:")
    lines.append("\t\treturn 0")
    lines.append("\tcase RestrictionLimited:")
    lines.append("\t\treturn 1")
    lines.append("\tcase RestrictionSemiLimited:")
    lines.append("\t\treturn 2")
    lines.append("\tdefault:")
    lines.append("\t\treturn 3")
    lines.append("\t}")
    lines.append("}")
    lines.append("")

    go_out.parent.mkdir(parents=True, exist_ok=True)
    with open(go_out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


# ─── Generate Go (models) ──────────────────────────────
def _go_type_needs_import(type_str):
    """Detect imports required by a Go type string."""
    imports = set()
    if "time.Time" in type_str or "time." in type_str:
        imports.add("time")
    if "json.RawMessage" in type_str:
        imports.add("encoding/json")
    if "civil.Date" in type_str or "civil." in type_str:
        imports.add("cloud.google.com/go/civil")
    return imports


def generate_go_models(*, out_dir):
    """Generate *_gen.go model files from models.yaml."""
    with open(MODELS_YAML, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    generated = []
    for file_def in data["files"]:
        file_target = file_def.get("target", "both")
        if file_target != "both" and file_target != "gateway":
            continue

        name = file_def["name"]
        out_path = Path(out_dir) / f"{name}_gen.go"

        lines = [
            _GENERATED_HEADER,
            "",
            "package model",
            "",
        ]

        declared_imports = set(file_def.get("imports", []))
        for td in file_def.get("types", []):
            for field in td.get("fields", []):
                declared_imports |= _go_type_needs_import(str(field["type"]))

        if declared_imports:
            std_imports = sorted(i for i in declared_imports if "/" not in i)
            ext_imports = sorted(i for i in declared_imports if "/" in i)
            lines.append("import (")
            for imp in std_imports:
                lines.append(f'\t"{imp}"')
            if std_imports and ext_imports:
                lines.append("")
            for imp in ext_imports:
                lines.append(f'\t"{imp}"')
            lines.append(")")
            lines.append("")

        for ta in file_def.get("type_aliases", []):
            lines.append(f"type {ta['name']} {ta['base']}")
        if file_def.get("type_aliases"):
            lines.append("")

        for cgroup in file_def.get("constants", []):
            ctype = cgroup["type"]
            lines.append("const (")
            for cv in cgroup["values"]:
                lines.append(f'\t{cv["name"]} {ctype} = "{cv["value"]}"')
            lines.append(")")
            lines.append("")

        for td in file_def.get("types", []):
            if td.get("comment"):
                lines.append(f"// {td['comment']}")
            lines.append(f"type {td['name']} struct {{")

            fields = td.get("fields", [])
            if fields:
                max_name_len = max(len(f["name"]) for f in fields)
                max_type_len = max(len(str(f["type"])) for f in fields)

            for field in fields:
                fname = field["name"]
                ftype = str(field["type"])
                tags = []
                if "json" in field:
                    tags.append(f'json:"{field["json"]}"')
                if "db" in field:
                    tags.append(f'db:"{field["db"]}"')
                tag_str = " ".join(tags)

                name_pad = " " * (max_name_len - len(fname) + 1)
                type_pad = " " * (max_type_len - len(ftype) + 1)

                if tag_str:
                    line = f"\t{fname}{name_pad}{ftype}{type_pad}`{tag_str}`"
                else:
                    line = f"\t{fname}{name_pad}{ftype}"

                if field.get("comment"):
                    line += f" // {field['comment']}"
                lines.append(line)

            lines.append("}")
            lines.append("")

        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
            f.write("\n")
        generated.append(name)

    return generated


# ─── Generate C# (constants) ───────────────────────────
def _cs_static_class(class_name, values, indent="    "):
    """Generate a C# static class with string constants."""
    lines = [f"public static class {class_name}"]
    lines.append("{")
    for v in values:
        name = _to_pascal(v)
        lines.append(f'{indent}public const string {name} = "{v}";')
    lines.append("}")
    lines.append("")
    return lines


def generate_csharp_constants(constants, *, out_path, namespace="OverloadParty.GameData"):
    """Generate GameConstants_gen.cs."""
    cs_out = Path(out_path)

    lines = [
        _GENERATED_HEADER,
        "",
        f"namespace {namespace};",
        "",
    ]

    iv = constants["initial_values"]
    lines.append("public static class GameConstants")
    lines.append("{")
    lines.append(f"    public const int DeckSize = {iv['deck_size']};")
    lines.append("}")
    lines.append("")

    # Factions (special: use value as-is).
    lines.append("public static class Factions")
    lines.append("{")
    for faction in constants["factions"]:
        lines.append(f'    public const string {faction} = "{faction}";')
    lines.append("}")
    lines.append("")

    lines.append("public static class SelectableFactions")
    lines.append("{")
    lines.append("    public static readonly string[] All = [")
    for f in constants["selectable_factions"]:
        lines.append(f"        Factions.{f},")
    lines.append("    ];")
    lines.append("}")
    lines.append("")

    for yaml_key, _, _, cs_class, _, _ in _SIMPLE_LIST_KEYS:
        values = constants.get(yaml_key)
        if values is None:
            continue
        lines.extend(_cs_static_class(cs_class, values))

    ws = constants["ws_message_types"]
    lines.append("public static class WSServerMsgTypes")
    lines.append("{")
    for v in ws["server"]:
        lines.append(f'    public const string {_to_pascal(v)} = "{v}";')
    lines.append("}")
    lines.append("")
    lines.append("public static class WSClientMsgTypes")
    lines.append("{")
    for v in ws["client"]:
        lines.append(f'    public const string {_to_pascal(v)} = "{v}";')
    lines.append("}")
    lines.append("")

    ct = constants["card_types"]
    all_types = ct["compute"] + ct["data"] + ct["support"]
    lines.append("public static class CardTypes")
    lines.append("{")
    for v in all_types:
        lines.append(f'    public const string {_to_pascal(v)} = "{v}";')
    lines.append("")

    compute_refs = ", ".join(_to_pascal(v) for v in ct["compute"])
    data_refs = ", ".join(_to_pascal(v) for v in ct["data"])
    support_non_attach = [t for t in ct["support"] if t != "Attachment"]
    support_refs = ", ".join(_to_pascal(v) for v in support_non_attach)

    lines.append(f"    public static readonly string[] ComputeTypes = [{compute_refs}];")
    lines.append(f"    public static readonly string[] DataTypes = [{data_refs}];")
    lines.append(f"    public static readonly string[] SupportTypes = [{support_refs}];")
    lines.append("")

    lines.append("    public static bool IsResourceType(string cardType) =>")
    lines.append("        Array.IndexOf(ComputeTypes, cardType) >= 0 || Array.IndexOf(DataTypes, cardType) >= 0;")
    lines.append("")
    lines.append("    public static bool IsFrontendEligible(string cardType) =>")
    lines.append(f"        Array.IndexOf(ComputeTypes, cardType) >= 0 || cardType == ObjectStorage;")
    lines.append("")
    lines.append("    public static bool IsBackendEligible(string cardType) =>")
    lines.append("        Array.IndexOf(DataTypes, cardType) >= 0 || Array.IndexOf(ComputeTypes, cardType) >= 0;")
    lines.append("")
    lines.append("    public static bool IsSupportType(string cardType) =>")
    lines.append("        Array.IndexOf(SupportTypes, cardType) >= 0;")
    lines.append("")
    lines.append("    public static bool IsAttachmentType(string cardType) =>")
    lines.append(f"        cardType == Attachment;")
    lines.append("")

    lines.append('    public static string GetCategory(string cardType)')
    lines.append("    {")
    lines.append("        if (Array.IndexOf(ComputeTypes, cardType) >= 0) return \"compute\";")
    lines.append("        if (Array.IndexOf(DataTypes, cardType) >= 0) return \"data\";")
    lines.append("        if (Array.IndexOf(SupportTypes, cardType) >= 0 || cardType == Attachment) return \"support\";")
    lines.append('        return "unknown";')
    lines.append("    }")

    lines.append("}")
    lines.append("")

    lines.append("public static class RestrictionHelper")
    lines.append("{")
    lines.append("    public static int CopyCount(string restriction) => restriction switch")
    lines.append("    {")
    lines.append(f'        RestrictionValues.Forbidden => 0,')
    lines.append(f'        RestrictionValues.Limited => 1,')
    lines.append(f'        RestrictionValues.SemiLimited => 2,')
    lines.append("        _ => 3,")
    lines.append("    };")
    lines.append("}")
    lines.append("")

    cs_out.parent.mkdir(parents=True, exist_ok=True)
    with open(cs_out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


# ─── Generate C# (event data) ──────────────────────────
_CS_TYPE_MAP = {
    "string": "string",
    "int": "int",
    "long": "long",
    "bool": "bool",
    "string[]": "List<string>",
}

_CS_NULLABLE_DEFAULTS = {
    "string": "string?",
    "int": "int?",
    "long": "long?",
    "bool": "bool?",
    "string[]": "List<string>?",
}


def generate_csharp_event_data(schemas, *, out_path, namespace="OverloadParty.GameData"):
    """Generate EventData_gen.cs."""
    cs_out = Path(out_path)

    lines = [
        _GENERATED_HEADER,
        "",
        f"namespace {namespace};",
        "",
    ]

    for event_type, fields in schemas.items():
        if event_type.startswith("_"):
            continue

        class_name = f"{_snake_to_pascal(event_type)}EventData"
        lines.append(f"public class {class_name}")
        lines.append("{")

        required_fields = []
        optional_fields = []

        for raw_key, raw_type in fields.items():
            optional = raw_key.endswith("?")
            key = raw_key.rstrip("?")
            cs_prop = _camel_to_pascal(key)

            if optional:
                cs_type = _CS_NULLABLE_DEFAULTS[raw_type]
                optional_fields.append((key, cs_prop, cs_type, raw_type))
            else:
                cs_type = _CS_TYPE_MAP[raw_type]
                init = ' = "";' if raw_type == "string" else " = [];" if raw_type == "string[]" else ""
                required_fields.append((key, cs_prop, cs_type, init))
                lines.append(f"    public required {cs_type} {cs_prop} {{ get; init; }}{init}")

        for key, cs_prop, cs_type, raw_type in optional_fields:
            lines.append(f"    public {cs_type} {cs_prop} {{ get; init; }}")

        lines.append("")
        lines.append("    public Dictionary<string, object> ToDictionary()")
        lines.append("    {")
        lines.append("        var d = new Dictionary<string, object>")
        lines.append("        {")
        for key, cs_prop, _, _ in required_fields:
            lines.append(f'            ["{key}"] = {cs_prop},')
        lines.append("        };")

        for key, cs_prop, _, _ in optional_fields:
            lines.append(f'        if ({cs_prop} is not null) d["{key}"] = {cs_prop};')

        lines.append("        return d;")
        lines.append("    }")
        lines.append("}")
        lines.append("")

    cs_out.parent.mkdir(parents=True, exist_ok=True)
    with open(cs_out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


# ─── Generate TypeScript (constants) ───────────────────
def _ts_const_array(const_name, type_name, values, extra_union=None):
    """Generate a TS as-const array with union type."""
    lines = []
    lines.append(f"export const {const_name} = {json.dumps(values)} as const;")
    if extra_union:
        lines.append(f"export type {type_name} = (typeof {const_name})[number] | {extra_union};")
    else:
        lines.append(f"export type {type_name} = (typeof {const_name})[number];")
    lines.append("")
    return lines


def generate_ts_constants(constants, *, out_path):
    """Generate constants.ts."""
    ts_out = Path(out_path)

    lines = [
        _GENERATED_HEADER,
        "",
    ]

    # Phases (special: includes 'selecting' in union type).
    lines.extend(_ts_const_array("PHASES", "GamePhase", constants["phases"], extra_union="'selecting'"))

    lines.extend(_ts_const_array("ZONES", "Zone", constants["zones"]))

    lines.extend(_ts_const_array("RANKS", "Rank", constants["ranks"]))

    # Instance families (special: includes '' in union type).
    lines.extend(_ts_const_array("INSTANCE_FAMILIES", "InstanceFamily", constants["instance_families"], extra_union="''"))

    lines.append(f"export const FACTIONS = {json.dumps(constants['factions'])} as const;")
    lines.append(f"export const SELECTABLE_FACTIONS = {json.dumps(constants['selectable_factions'])} as const;")
    lines.append("export type FactionId = (typeof SELECTABLE_FACTIONS)[number];")
    display_names = constants.get("faction_display_names", {})
    display_entries = ", ".join(f'"{f}": "{display_names.get(f, f)}"' for f in constants["factions"])
    lines.append(f"export const FACTION_DISPLAY_NAMES: Record<string, string> = {{ {display_entries} }};")
    lines.append("")

    _ts_skip = {"phases", "zones", "ranks", "instance_families"}
    for yaml_key, _, _, _, ts_const, ts_type in _SIMPLE_LIST_KEYS:
        if yaml_key in _ts_skip:
            continue
        values = constants.get(yaml_key)
        if values is None:
            continue
        lines.extend(_ts_const_array(ts_const, ts_type, values))

    ct = constants["card_types"]
    all_card_types = ct["compute"] + ct["data"] + ct["support"]
    lines.append(f"export const CARD_TYPES = {json.dumps(all_card_types)} as const;")
    lines.append("export type CardType = (typeof CARD_TYPES)[number];")
    lines.append("")

    compute_set = json.dumps(ct["compute"])
    data_set = json.dumps(ct["data"])
    lines.append(f"const COMPUTE_TYPES: ReadonlySet<string> = new Set({compute_set});")
    lines.append(f"const DATA_TYPES: ReadonlySet<string> = new Set({data_set});")
    lines.append("")

    lines.append("/** Returns true if the card type is a deployable resource (compute, AI/ML, or data). */")
    lines.append("export function isResourceType(cardType: string): boolean {")
    lines.append("  return COMPUTE_TYPES.has(cardType) || DATA_TYPES.has(cardType);")
    lines.append("}")
    lines.append("")

    lines.append("/** Returns true if the card can be placed in the frontend zone. */")
    lines.append("export function isFrontendEligible(cardType: string): boolean {")
    lines.append("  return COMPUTE_TYPES.has(cardType) || cardType === 'ObjectStorage';")
    lines.append("}")
    lines.append("")

    lines.append("/** Returns true if the card can be placed in the backend zone. */")
    lines.append("export function isBackendEligible(cardType: string): boolean {")
    lines.append("  return DATA_TYPES.has(cardType) || COMPUTE_TYPES.has(cardType);")
    lines.append("}")
    lines.append("")

    lines.append("/** Returns true if the card goes in the support zone (Platform, Strategy, Incident, Reactive). */")
    lines.append("export function isSupportType(cardType: string): boolean {")
    support_types = [t for t in ct["support"] if t not in ("Attachment",)]
    support_cases = " || ".join(f"cardType === '{t}'" for t in support_types)
    lines.append(f"  return {support_cases};")
    lines.append("}")
    lines.append("")

    lines.append("/** Returns true if the card is an Attachment (attaches to resources, not support zone). */")
    lines.append("export function isAttachmentType(cardType: string): boolean {")
    lines.append("  return cardType === 'Attachment';")
    lines.append("}")
    lines.append("")

    ws_types = constants["ws_message_types"]
    lines.append(f"export const WS_SERVER_MSG_TYPES = {json.dumps(ws_types['server'])} as const;")
    lines.append("export type WSServerMsgType = (typeof WS_SERVER_MSG_TYPES)[number];")
    lines.append(f"export const WS_CLIENT_MSG_TYPES = {json.dumps(ws_types['client'])} as const;")
    lines.append("export type WSClientMsgType = (typeof WS_CLIENT_MSG_TYPES)[number];")
    lines.append("")

    lines.append("/** Returns the maximum number of copies allowed in a deck for a given restriction. */")
    lines.append("export function restrictionCopyCount(restriction: Restriction): number {")
    lines.append("  switch (restriction) {")
    lines.append("    case 'forbidden': return 0;")
    lines.append("    case 'limited': return 1;")
    lines.append("    case 'semi_limited': return 2;")
    lines.append("    case 'unlimited': return 3;")
    lines.append("    default: return 3;")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    iv = constants["initial_values"]
    lines.append("export const INITIAL_VALUES = {")
    for key, val in iv.items():
        camel = re.sub(r'_([a-z])', lambda m: m.group(1).upper(), key)
        lines.append(f"  {camel}: {val},")
    lines.append("} as const;")
    lines.append("")

    ts_out.parent.mkdir(parents=True, exist_ok=True)
    with open(ts_out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


# ─── Generate TypeScript (event data) ──────────────────
_TS_TYPE_MAP = {
    "string": "string",
    "int": "number",
    "long": "number",
    "bool": "boolean",
    "string[]": "string[]",
}


def generate_ts_event_data(schemas, *, out_path):
    """Generate eventData.ts."""
    ts_out = Path(out_path)

    lines = [
        _GENERATED_HEADER,
        "",
    ]

    type_names = []

    for event_type, fields in schemas.items():
        if event_type.startswith("_"):
            continue

        type_name = f"{_snake_to_pascal(event_type)}EventData"
        type_names.append((event_type, type_name))

        lines.append(f"export interface {type_name} {{")
        for raw_key, raw_type in fields.items():
            optional = raw_key.endswith("?")
            key = raw_key.rstrip("?")
            ts_type = _TS_TYPE_MAP[raw_type]
            opt = "?" if optional else ""
            lines.append(f"  {key}{opt}: {ts_type};")
        lines.append("}")
        lines.append("")

    lines.append("export interface EventDataMap {")
    for event_type, type_name in type_names:
        lines.append(f"  {event_type}: {type_name};")
    lines.append("}")
    lines.append("")

    ts_out.parent.mkdir(parents=True, exist_ok=True)
    with open(ts_out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


# ─── Generate TypeScript (WS messages) ─────────────────
_GO_TO_TS_TYPE = {
    "string": "string",
    "int": "number",
    "int64": "number",
    "bool": "boolean",
    "json.RawMessage": "Record<string, unknown>",
}


def generate_ts_ws_messages(*, out_path):
    """Generate wsMessages.ts from the ws_messages section of models.yaml."""
    with open(MODELS_YAML, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    ws_file = None
    for file_def in data["files"]:
        if file_def["name"] == "ws_messages":
            ws_file = file_def
            break

    if ws_file is None:
        print("WARNING: ws_messages not found in models.yaml, skipping TS generation", file=sys.stderr)
        return

    ts_out = Path(out_path)

    lines = [
        _GENERATED_HEADER,
        "",
    ]

    for td in ws_file.get("types", []):
        name = td["name"]
        if td.get("comment"):
            lines.append(f"/** {td['comment']} */")
        lines.append(f"export interface {name} {{")
        for field in td.get("fields", []):
            json_tag = field["json"]
            optional = json_tag.endswith(",omitempty")
            json_key = json_tag.split(",")[0]
            go_type = str(field["type"])
            ts_type = _GO_TO_TS_TYPE.get(go_type, "unknown")
            opt = "?" if optional else ""
            lines.append(f"  {json_key}{opt}: {ts_type};")
        lines.append("}")
        lines.append("")

    ts_out.parent.mkdir(parents=True, exist_ok=True)
    with open(ts_out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


# ─── Generate C# (variant types) ─────────────────────────
def generate_csharp_variant_types(variant_types, *, out_path, namespace="OverloadParty.GameData"):
    """Generate VariantTypes_gen.cs from variant_types in models.yaml.

    Each variant type becomes a flat C# class where the discriminator field
    is required and all variant-specific fields are nullable.
    """
    cs_out = Path(out_path)

    lines = [
        _GENERATED_HEADER,
        "",
        f"namespace {namespace};",
        "",
    ]

    for vt in variant_types:
        name = vt["name"]
        discriminator = vt["discriminator"]
        disc_prop = _snake_to_pascal(discriminator)

        if vt.get("comment"):
            lines.append(f"/// <summary>{vt['comment']}</summary>")

        lines.append(f"public class {name}")
        lines.append("{")

        # Discriminator field (always required string).
        lines.append(f'    public required string {disc_prop} {{ get; init; }} = "";')

        seen = {}  # field_name -> (cs_prop, cs_nullable_type)
        for variant in vt["variants"]:
            for field in variant.get("fields", []):
                fname = field["name"]
                if fname in seen:
                    continue
                cs_prop = _snake_to_pascal(fname)
                raw_type = field["type"]
                cs_type = _CS_NULLABLE_DEFAULTS[raw_type]
                seen[fname] = (cs_prop, cs_type)

        for cs_prop, cs_type in seen.values():
            lines.append(f"    public {cs_type} {cs_prop} {{ get; init; }}")

        lines.append("}")
        lines.append("")

    cs_out.parent.mkdir(parents=True, exist_ok=True)
    with open(cs_out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


# ─── Generate TypeScript (variant types) ─────────────────
def generate_ts_variant_types(variant_types, *, out_path):
    """Generate variantTypes.ts from variant_types in models.yaml.

    Each variant type becomes a TS discriminated union where the
    discriminator field has a string literal type per variant.
    """
    ts_out = Path(out_path)

    ref_types: set[str] = set()
    for vt in variant_types:
        for variant in vt.get("variants", []):
            for field in variant.get("fields", []):
                ref = field.get("ref")
                if ref:
                    ref_types.add(ref)

    lines = [
        _GENERATED_HEADER,
        "",
    ]

    if ref_types:
        sorted_refs = sorted(ref_types)
        lines.append(f"import type {{ {', '.join(sorted_refs)} }} from './constants';")
        lines.append("")

    for vt in variant_types:
        name = vt["name"]
        discriminator = vt["discriminator"]

        if vt.get("comment"):
            lines.append(f"/** {vt['comment']} */")

        variant_lines = []
        for variant in vt["variants"]:
            value = variant["value"]
            fields = [f"{discriminator}: '{value}'"]
            for field in variant.get("fields", []):
                fname = field["name"]
                ref = field.get("ref")
                ts_type = ref if ref else _TS_TYPE_MAP[field["type"]]
                opt = "?" if field.get("optional") else ""
                fields.append(f"{fname}{opt}: {ts_type}")
            variant_lines.append("  | { " + "; ".join(fields) + " }")

        lines.append(f"export type {name} =")
        for vl in variant_lines:
            lines.append(vl)
        lines[-1] = lines[-1] + ";"
        lines.append("")

    ts_out.parent.mkdir(parents=True, exist_ok=True)
    with open(ts_out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


# ─── Main ──────────────────────────────────────────────
def main():
    with open(CONSTANTS_YAML, "r", encoding="utf-8") as f:
        constants = yaml.safe_load(f)
    with open(EVENT_SCHEMAS_YAML, "r", encoding="utf-8") as f:
        event_schemas = yaml.safe_load(f)
    with open(MODELS_YAML, "r", encoding="utf-8") as f:
        models = yaml.safe_load(f)

    variant_types = models.get("variant_types", [])

    # Go
    generate_go_constants(constants, out_path=GO_DIR / "constants" / "constants_gen.go")
    print("Generated → packages/gamedata/constants/constants_gen.go", file=sys.stderr)

    model_names = generate_go_models(out_dir=GO_DIR / "model")
    print(f"Generated models → packages/gamedata/model/ [{', '.join(model_names)}]", file=sys.stderr)

    # C#
    generate_csharp_constants(constants, out_path=DOTNET_DIR / "GameConstants_gen.cs")
    print("Generated → packages/dotnet/GameConstants_gen.cs", file=sys.stderr)

    generate_csharp_event_data(event_schemas, out_path=DOTNET_DIR / "EventData_gen.cs")
    print("Generated → packages/dotnet/EventData_gen.cs", file=sys.stderr)

    if variant_types:
        generate_csharp_variant_types(variant_types, out_path=DOTNET_DIR / "VariantTypes_gen.cs")
        print("Generated → packages/dotnet/VariantTypes_gen.cs", file=sys.stderr)

    # TypeScript
    generate_ts_constants(constants, out_path=NPM_DIR / "src" / "constants.ts")
    print("Generated → packages/npm/src/constants.ts", file=sys.stderr)

    generate_ts_event_data(event_schemas, out_path=NPM_DIR / "src" / "eventData.ts")
    print("Generated → packages/npm/src/eventData.ts", file=sys.stderr)

    generate_ts_ws_messages(out_path=NPM_DIR / "src" / "wsMessages.ts")
    print("Generated → packages/npm/src/wsMessages.ts", file=sys.stderr)

    if variant_types:
        generate_ts_variant_types(variant_types, out_path=NPM_DIR / "src" / "variantTypes.ts")
        print("Generated → packages/npm/src/variantTypes.ts", file=sys.stderr)


if __name__ == "__main__":
    main()
