#!/usr/bin/env python3
"""YAML 定義からゲームデザイン定数を Go / C# / TypeScript に生成します。

出力:
  - packages/game-design-constants/constants_gen.go         (Go module)
  - packages/game-design-constants-dotnet/GameDesignConstants_gen.cs (NuGet)
  - packages/game-design-constants-npm/src/index.ts         (npm package)

ソース:
  - data/game_design_constants.yaml
  - data/factions.yaml

使い方:
    python3 scripts/generate_constants.py
"""

import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"

GAME_DESIGN_YAML = DATA_DIR / "game_design_constants.yaml"
FACTIONS_YAML = DATA_DIR / "factions.yaml"

PACKAGES_DIR = ROOT / "packages"

GO_GAME_DESIGN_DIR = PACKAGES_DIR / "game-design-constants"
DOTNET_GAME_DESIGN_DIR = PACKAGES_DIR / "game-design-constants-dotnet"
NPM_GAME_DESIGN_DIR = PACKAGES_DIR / "game-design-constants-npm"


_GENERATED_HEADER = "// Code generated by scripts/generate_constants.py; DO NOT EDIT."


def _to_pascal(value):
    """YAML 値を PascalCase 識別子に変換します。"""
    value = value.replace("/", "")
    if "_" in value or "-" in value:
        return "".join(w.title() for w in value.replace("-", "_").split("_"))
    if value and value[0].isupper():
        return value
    return value.title() if value else value


@dataclass(frozen=True)
class EnumCodegenRule:
    """YAML の flat string list を 3 言語の string const 列挙型として codegen するルール。

    対象は data/game_design_constants.yaml のトップレベルキーのうち、値が単純な
    文字列配列 (`["a", "b", "c"]`) になっているもの。faction metadata のような
    構造体 codegen や card_types のような入れ子分類は対象外。
    """

    yaml_key: str
    go_prefix: str
    go_comment: str
    cs_class: str
    ts_const: str
    ts_type: str
    # TS の union 型に追加する追加リテラル (例: "''" で空文字許容)。
    # 業務ルール上 YAML の値以外に特定リテラルを許容したい場合のみ指定する。
    ts_extra_union: str | None = None


ENUM_CODEGEN_RULES = [
    EnumCodegenRule("zones", "Zone", "Zones", "Zones", "ZONES", "Zone"),
    EnumCodegenRule("ranks", "Rank", "Ranks", "Ranks", "RANKS", "Rank"),
    EnumCodegenRule("instance_families", "InstanceFamily", "Instance families", "InstanceFamilies", "INSTANCE_FAMILIES", "InstanceFamily", ts_extra_union="''"),
    EnumCodegenRule("restriction_values", "Restriction", "Restriction values", "RestrictionValues", "RESTRICTION_VALUES", "Restriction"),
    EnumCodegenRule("match_types", "MatchType", "Match types", "MatchTypes", "MATCH_TYPES", "MatchType"),
    EnumCodegenRule("stat_types", "StatType", "Stat types", "StatTypes", "STAT_TYPES", "StatType"),
]


def _write_file(out_path, lines):
    """生成結果をファイルに書き出します。"""
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


def _go_const_block(comment, prefix, values):
    """Go の const ブロックを生成します。"""
    lines = [f"// {comment}."]
    lines.append("const (")
    for v in values:
        name = f"{prefix}{_to_pascal(v)}"
        lines.append(f'\t{name} = "{v}"')
    lines.append(")")
    lines.append("")
    return lines


def _go_header(package):
    """Go ファイルのヘッダーを生成します。"""
    return [
        _GENERATED_HEADER,
        "",
        f"package {package}",
        "",
    ]


def generate_go_game_design(data, factions):
    """Go の game-design-constants パッケージを生成します。"""
    lines = _go_header("game_design")

    iv = data["initial_values"]
    lines.append("// Deck size.")
    lines.append("const (")
    lines.append(f"\tDeckSize = {iv['deck_size']}")
    lines.append(")")
    lines.append("")

    sorted_factions = sorted(factions, key=lambda f: f["sort_order"])
    lines.append("// Factions.")
    lines.append("const (")
    for f in sorted_factions:
        lines.append(f'\tFaction{f["id"]} = "{f["id"]}"')
    lines.append(")")
    lines.append("")

    selectable = [f for f in sorted_factions if f.get("is_collectible")]
    lines.append("// SelectableFactions is the list of factions players can choose.")
    lines.append("var SelectableFactions = []string{")
    for f in selectable:
        lines.append(f"\tFaction{f['id']},")
    lines.append("}")
    lines.append("")

    lines.append("// FactionMetadata holds display and ordering information for a faction.")
    lines.append("type FactionMetadata struct {")
    lines.append("\tID            string")
    lines.append("\tShortNameJa   string")
    lines.append("\tShortNameEn   string")
    lines.append("\tFullNameJa    string")
    lines.append("\tFullNameEn    string")
    lines.append("\tIsCollectible bool")
    lines.append("\tSortOrder     int")
    lines.append("}")
    lines.append("")

    lines.append("// FactionsMetadata lists all factions in sort order.")
    lines.append("var FactionsMetadata = []FactionMetadata{")
    for f in sorted_factions:
        lines.append("\t{")
        lines.append(f'\t\tID:            "{f["id"]}",')
        lines.append(f'\t\tShortNameJa:   {json.dumps(f["short_name_ja"], ensure_ascii=False)},')
        lines.append(f'\t\tShortNameEn:   {json.dumps(f["short_name_en"], ensure_ascii=False)},')
        lines.append(f'\t\tFullNameJa:    {json.dumps(f["full_name_ja"], ensure_ascii=False)},')
        lines.append(f'\t\tFullNameEn:    {json.dumps(f["full_name_en"], ensure_ascii=False)},')
        lines.append(f'\t\tIsCollectible: {"true" if f["is_collectible"] else "false"},')
        lines.append(f'\t\tSortOrder:     {f["sort_order"]},')
        lines.append("\t},")
    lines.append("}")
    lines.append("")

    lines.append("// FactionByID looks up faction metadata by ID.")
    lines.append("var FactionByID = map[string]FactionMetadata{")
    for f in sorted_factions:
        lines.append(f'\t"{f["id"]}": FactionsMetadata[{sorted_factions.index(f)}],')
    lines.append("}")
    lines.append("")

    for rule in ENUM_CODEGEN_RULES:
        values = data.get(rule.yaml_key)
        if values is None:
            continue
        lines.extend(_go_const_block(rule.go_comment, rule.go_prefix, values))

    # `log` サブカテゴリは内部ログカード専用のため除外
    ct = data["card_types"]
    all_types = ct["compute"] + ct["data"] + ct["support"]
    lines.append("// Card types.")
    lines.append("const (")
    for v in all_types:
        lines.append(f'\tCardType{_to_pascal(v)} = "{v}"')
    lines.append(")")
    lines.append("")

    _write_file(GO_GAME_DESIGN_DIR / "constants_gen.go", lines)


def _cs_static_class(class_name, values, indent="    "):
    """C# の static class（string 定数群）を生成します。"""
    lines = [f"public static class {class_name}"]
    lines.append("{")
    for v in values:
        name = _to_pascal(v)
        lines.append(f'{indent}public const string {name} = "{v}";')
    lines.append("}")
    lines.append("")
    return lines


def _cs_header(namespace):
    """C# ファイルのヘッダーを生成します。"""
    return [
        _GENERATED_HEADER,
        "",
        f"namespace {namespace};",
        "",
    ]


def generate_csharp_game_design(data, factions):
    """C# の game-design-constants NuGet パッケージを生成します。"""
    lines = _cs_header("OverloadParty.GameDesignConstants")

    iv = data["initial_values"]
    lines.append("public static class InitialValues")
    lines.append("{")
    lines.append(f"    public const int DeckSize = {iv['deck_size']};")
    lines.append("}")
    lines.append("")

    sorted_factions = sorted(factions, key=lambda f: f["sort_order"])

    lines.append("public static class Factions")
    lines.append("{")
    for f in sorted_factions:
        lines.append(f'    public const string {f["id"]} = "{f["id"]}";')
    lines.append("}")
    lines.append("")

    selectable = [f for f in sorted_factions if f.get("is_collectible")]
    lines.append("public static class SelectableFactions")
    lines.append("{")
    lines.append("    public static readonly string[] All = [")
    for f in selectable:
        lines.append(f"        Factions.{f['id']},")
    lines.append("    ];")
    lines.append("}")
    lines.append("")

    lines.append("public record FactionMetadata(")
    lines.append("    string Id,")
    lines.append("    string ShortNameJa,")
    lines.append("    string ShortNameEn,")
    lines.append("    string FullNameJa,")
    lines.append("    string FullNameEn,")
    lines.append("    bool IsCollectible,")
    lines.append("    int SortOrder")
    lines.append(");")
    lines.append("")

    lines.append("public static class FactionsMetadata")
    lines.append("{")
    lines.append("    public static readonly FactionMetadata[] All = [")
    for f in sorted_factions:
        is_col = "true" if f["is_collectible"] else "false"
        ja_short = json.dumps(f["short_name_ja"], ensure_ascii=False)
        en_short = json.dumps(f["short_name_en"], ensure_ascii=False)
        ja_full = json.dumps(f["full_name_ja"], ensure_ascii=False)
        en_full = json.dumps(f["full_name_en"], ensure_ascii=False)
        lines.append(
            f'        new FactionMetadata("{f["id"]}", {ja_short}, {en_short}, '
            f'{ja_full}, {en_full}, {is_col}, {f["sort_order"]}),'
        )
    lines.append("    ];")
    lines.append("")
    lines.append("    public static readonly System.Collections.Generic.Dictionary<string, FactionMetadata> ById =")
    lines.append("        System.Linq.Enumerable.ToDictionary(All, m => m.Id);")
    lines.append("}")
    lines.append("")

    for rule in ENUM_CODEGEN_RULES:
        values = data.get(rule.yaml_key)
        if values is None:
            continue
        lines.extend(_cs_static_class(rule.cs_class, values))

    ct = data["card_types"]
    all_types = ct["compute"] + ct["data"] + ct["support"]
    lines.append("public static class CardTypes")
    lines.append("{")
    for v in all_types:
        lines.append(f'    public const string {_to_pascal(v)} = "{v}";')
    lines.append("}")
    lines.append("")

    _write_file(DOTNET_GAME_DESIGN_DIR / "GameDesignConstants_gen.cs", lines)


def _ts_const_array(const_name, type_name, values, extra_union=None):
    """TypeScript の as const 配列と union type を生成します。"""
    lines = []
    lines.append(f"export const {const_name} = {json.dumps(values)} as const;")
    if extra_union:
        lines.append(f"export type {type_name} = (typeof {const_name})[number] | {extra_union};")
    else:
        lines.append(f"export type {type_name} = (typeof {const_name})[number];")
    lines.append("")
    return lines


def _ts_header():
    """TypeScript ファイルのヘッダーを生成します。"""
    return [
        _GENERATED_HEADER,
        "",
    ]


def generate_ts_game_design(data, factions):
    """TypeScript の game-design-constants npm パッケージを生成します。"""
    lines = _ts_header()

    for rule in ENUM_CODEGEN_RULES:
        values = data.get(rule.yaml_key)
        if values is None:
            continue
        lines.extend(_ts_const_array(rule.ts_const, rule.ts_type, values, extra_union=rule.ts_extra_union))

    ct = data["card_types"]
    all_card_types = ct["compute"] + ct["data"] + ct["support"]
    lines.append(f"export const CARD_TYPES = {json.dumps(all_card_types)} as const;")
    lines.append("export type CardType = (typeof CARD_TYPES)[number];")
    lines.append("")

    sorted_factions = sorted(factions, key=lambda f: f["sort_order"])
    all_faction_ids = [f["id"] for f in sorted_factions]
    selectable_ids = [f["id"] for f in sorted_factions if f.get("is_collectible")]

    lines.append(f"export const FACTIONS = {json.dumps(all_faction_ids)} as const;")
    lines.append(f"export const SELECTABLE_FACTIONS = {json.dumps(selectable_ids)} as const;")
    lines.append("export type FactionId = (typeof SELECTABLE_FACTIONS)[number];")
    lines.append("")

    lines.append("export interface FactionMetadata {")
    lines.append("  id: string;")
    lines.append("  shortNameJa: string;")
    lines.append("  shortNameEn: string;")
    lines.append("  fullNameJa: string;")
    lines.append("  fullNameEn: string;")
    lines.append("  isCollectible: boolean;")
    lines.append("  sortOrder: number;")
    lines.append("}")
    lines.append("")

    lines.append("export const FACTIONS_METADATA: readonly FactionMetadata[] = [")
    for f in sorted_factions:
        entry = {
            "id": f["id"],
            "shortNameJa": f["short_name_ja"],
            "shortNameEn": f["short_name_en"],
            "fullNameJa": f["full_name_ja"],
            "fullNameEn": f["full_name_en"],
            "isCollectible": f["is_collectible"],
            "sortOrder": f["sort_order"],
        }
        lines.append(f"  {json.dumps(entry, ensure_ascii=False)},")
    lines.append("];")
    lines.append("")

    lines.append("export const FACTION_BY_ID: Record<string, FactionMetadata> = {")
    for f in sorted_factions:
        lines.append(f'  "{f["id"]}": FACTIONS_METADATA[{sorted_factions.index(f)}],')
    lines.append("};")
    lines.append("")

    iv = data["initial_values"]
    lines.append("export const INITIAL_VALUES = {")
    for key, val in iv.items():
        camel = re.sub(r'_([a-z])', lambda m: m.group(1).upper(), key)
        lines.append(f"  {camel}: {val},")
    lines.append("} as const;")
    lines.append("")

    _write_file(NPM_GAME_DESIGN_DIR / "src" / "index.ts", lines)


def _load_yaml(path):
    """YAML ファイルを読み込みます。"""
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def main():
    """全言語の定数ファイルを生成します。"""
    game_design = _load_yaml(GAME_DESIGN_YAML)
    factions_doc = _load_yaml(FACTIONS_YAML)
    factions = factions_doc["factions"]

    generate_go_game_design(game_design, factions)
    print("Generated → packages/game-design-constants/constants_gen.go", file=sys.stderr)

    generate_csharp_game_design(game_design, factions)
    print("Generated → packages/game-design-constants-dotnet/GameDesignConstants_gen.cs", file=sys.stderr)

    generate_ts_game_design(game_design, factions)
    print("Generated → packages/game-design-constants-npm/src/index.ts", file=sys.stderr)


if __name__ == "__main__":
    main()
