#!/usr/bin/env python3
"""Generate product data outputs from YAML product definitions.

Outputs:
  - packages/devdata/cache/products_gen.json   (Go embedded, local dev)
  - db/seed/products.sql                       (PostgreSQL UPSERT seed)

Usage:
    python3 scripts/generate_products.py
"""

import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

# ─── Paths ──────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
YAML_PATH = ROOT / "data" / "mock" / "products.yaml"
SEED_OUT = ROOT / "db" / "seed" / "products.sql"
GO_JSON_OUT = ROOT / "packages" / "devdata" / "cache" / "products_gen.json"

# ─── Constants ──────────────────────────────────────────
VALID_TYPES = {"faction_set", "cosmetic", "subscription"}


# ─── Load ───────────────────────────────────────────────
def load_products():
    with open(YAML_PATH, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return data.get("products", [])


# ─── Validate ──────────────────────────────────────────
def validate(products):
    errors = []
    seen_ids = {}

    for i, p in enumerate(products):
        label = p.get("product_id", f"index={i}")

        for field in ("product_id", "name", "type", "price", "content", "is_active"):
            if field not in p:
                errors.append(f"{label}: missing required field '{field}'")

        pid = p.get("product_id", "")
        if pid in seen_ids:
            errors.append(f"{label}: duplicate product_id")
        else:
            seen_ids[pid] = True

        ptype = p.get("type", "")
        if ptype and ptype not in VALID_TYPES:
            errors.append(f"{label}: invalid type '{ptype}'")

        price = p.get("price")
        if price is not None and (not isinstance(price, int) or price < 0):
            errors.append(f"{label}: price must be a non-negative integer")

    return errors


# ─── Generate JSON ─────────────────────────────────────
def generate_json(products, *, out_path):
    output = []
    for p in products:
        entry = {
            "product_id": p["product_id"],
            "name": p["name"],
            "type": p["type"],
            "price": p["price"],
            "content": p["content"],
            "is_active": p["is_active"],
        }
        if p.get("faction_id") is not None:
            entry["faction_id"] = p["faction_id"]
        if p.get("description") is not None:
            entry["description"] = p["description"]
        if p.get("image_url") is not None:
            entry["image_url"] = p["image_url"]
        output.append(entry)

    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
        f.write("\n")

    return len(output)


# ─── Generate Seed SQL ─────────────────────────────────
def _sql_escape(s):
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def generate_seed_sql(products, *, out_path):
    out = Path(out_path)

    lines = []
    lines.append("-- Auto-generated by scripts/generate_products.py. DO NOT EDIT.")
    lines.append("")
    lines.append("INSERT INTO products")
    lines.append("  (product_id, name, type, price, content, faction_id, description, image_url, is_active)")
    lines.append("VALUES")

    value_rows = []
    for p in products:
        pid = _sql_escape(p["product_id"])
        name = _sql_escape(p["name"])
        ptype = _sql_escape(p["type"])
        price = str(p["price"])
        content = _sql_escape(json.dumps(p["content"], ensure_ascii=False)) + "::jsonb"
        faction_id = _sql_escape(p.get("faction_id"))
        description = _sql_escape(p.get("description"))
        image_url = _sql_escape(p.get("image_url"))
        is_active = "true" if p["is_active"] else "false"

        row = f"  ({pid}, {name}, {ptype}, {price}, {content}, {faction_id}, {description}, {image_url}, {is_active})"
        value_rows.append(row)

    lines.append(",\n".join(value_rows))
    lines.append("")
    lines.append("ON CONFLICT (product_id) DO UPDATE SET")
    lines.append("  name        = EXCLUDED.name,")
    lines.append("  type        = EXCLUDED.type,")
    lines.append("  price       = EXCLUDED.price,")
    lines.append("  content     = EXCLUDED.content,")
    lines.append("  faction_id  = EXCLUDED.faction_id,")
    lines.append("  description = EXCLUDED.description,")
    lines.append("  image_url   = EXCLUDED.image_url,")
    lines.append("  is_active   = EXCLUDED.is_active;")
    lines.append("")

    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return len(products)


# ─── Main ──────────────────────────────────────────────
def main():
    if not YAML_PATH.exists():
        print(f"ERROR: YAML file not found: {YAML_PATH}", file=sys.stderr)
        sys.exit(1)

    products = load_products()
    if not products:
        print("ERROR: No products loaded from YAML", file=sys.stderr)
        sys.exit(1)

    errors = validate(products)
    if errors:
        print(f"Validation failed with {len(errors)} error(s):", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        sys.exit(1)

    json_count = generate_json(products, out_path=GO_JSON_OUT)
    print(f"Generated {json_count} products → {GO_JSON_OUT.relative_to(ROOT)}", file=sys.stderr)

    seed_count = generate_seed_sql(products, out_path=SEED_OUT)
    print(f"Generated {seed_count} products → {SEED_OUT.relative_to(ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
