"""generate_constants.py のユニットテスト。"""

import textwrap

import pytest

import generate_constants as gen


# ─── Golden fixture ─────────────────────────────────────
# 固定の小さな入力で 3 言語の出力を完全一致検証する。出力仕様
# (フィールド順・特殊ルール "instance_families の空文字 union" など) が
# 意図せず変わった場合に即座に壊れる。

@pytest.fixture
def fixture_data():
    return {
        "zones": ["frontend", "backend"],
        "ranks": ["small", "medium"],
        "instance_families": ["M", "C"],
        "restriction_values": ["forbidden", "limited"],
        "restriction_copy_count": {"forbidden": 0, "limited": 1},
        "match_types": ["pvp"],
        "stat_types": ["tp"],
        "card_types": ["Compute", "Platform"],
        "subtypes": {
            "Compute": ["VM"],
        },
        "initial_values": {"deck_size": 30},
    }


@pytest.fixture
def fixture_factions():
    return [
        {
            "id": "SHE",
            "short_name_ja": "SHE",
            "short_name_en": "SHE",
            "full_name_ja": "SHE Full",
            "full_name_en": "SHE Full",
            "is_collectible": True,
            "sort_order": 1,
        },
        {
            "id": "Neutral",
            "short_name_ja": "Neutral",
            "short_name_en": "Neutral",
            "full_name_ja": "Neutral",
            "full_name_en": "Neutral",
            "is_collectible": False,
            "sort_order": 0,
        },
    ]


class TestGoldenGo:
    def test_go_output_matches(self, tmp_path, monkeypatch, fixture_data, fixture_factions):
        monkeypatch.setattr(gen, "GO_GAME_DESIGN_DIR", tmp_path)
        gen.generate_go_game_design(fixture_data, fixture_factions)
        got = (tmp_path / "constants_gen.go").read_text()
        expected = textwrap.dedent('''\
            // Code generated by scripts/generate_constants.py; DO NOT EDIT.

            package game_design

            // Deck size.
            const (
            \tDeckSize = 30
            )

            // Factions.
            const (
            \tFactionNeutral = "Neutral"
            \tFactionSHE = "SHE"
            )

            // SelectableFactions is the list of factions players can choose.
            var SelectableFactions = []string{
            \tFactionSHE,
            }

            // FactionMetadata holds display and ordering information for a faction.
            type FactionMetadata struct {
            \tID            string
            \tShortNameJa   string
            \tShortNameEn   string
            \tFullNameJa    string
            \tFullNameEn    string
            \tIsCollectible bool
            \tSortOrder     int
            }

            // FactionsMetadata lists all factions in sort order.
            var FactionsMetadata = []FactionMetadata{
            \t{
            \t\tID:            "Neutral",
            \t\tShortNameJa:   "Neutral",
            \t\tShortNameEn:   "Neutral",
            \t\tFullNameJa:    "Neutral",
            \t\tFullNameEn:    "Neutral",
            \t\tIsCollectible: false,
            \t\tSortOrder:     0,
            \t},
            \t{
            \t\tID:            "SHE",
            \t\tShortNameJa:   "SHE",
            \t\tShortNameEn:   "SHE",
            \t\tFullNameJa:    "SHE Full",
            \t\tFullNameEn:    "SHE Full",
            \t\tIsCollectible: true,
            \t\tSortOrder:     1,
            \t},
            }

            // FactionByID looks up faction metadata by ID.
            var FactionByID = map[string]FactionMetadata{
            \t"Neutral": FactionsMetadata[0],
            \t"SHE": FactionsMetadata[1],
            }

            // Zones.
            const (
            \tZoneFrontend = "frontend"
            \tZoneBackend = "backend"
            )

            // Ranks.
            const (
            \tRankSmall = "small"
            \tRankMedium = "medium"
            )

            // Instance families.
            const (
            \tInstanceFamilyM = "M"
            \tInstanceFamilyC = "C"
            )

            // Restriction values.
            const (
            \tRestrictionForbidden = "forbidden"
            \tRestrictionLimited = "limited"
            )

            // Match types.
            const (
            \tMatchTypePvp = "pvp"
            )

            // Stat types.
            const (
            \tStatTypeTp = "tp"
            )

            // Card types.
            const (
            \tCardTypeCompute = "Compute"
            \tCardTypePlatform = "Platform"
            )

            // Card subtypes (Compute).
            const (
            \tSubtypeComputeVM = "VM"
            )

            // RestrictionCopyCount returns the deck investment cap per restriction value.
            var RestrictionCopyCount = map[string]int{
            \tRestrictionForbidden: 0,
            \tRestrictionLimited: 1,
            }

            ''')
        assert got == expected


class TestGoldenCSharp:
    def test_csharp_output_matches(self, tmp_path, monkeypatch, fixture_data, fixture_factions):
        monkeypatch.setattr(gen, "DOTNET_GAME_DESIGN_DIR", tmp_path)
        gen.generate_csharp_game_design(fixture_data, fixture_factions)
        got = (tmp_path / "GameDesignConstants_gen.cs").read_text()
        expected = textwrap.dedent('''\
            // Code generated by scripts/generate_constants.py; DO NOT EDIT.

            namespace OverloadParty.GameDesignConstants;

            public static class InitialValues
            {
                public const int DeckSize = 30;
            }

            public static class Factions
            {
                public const string Neutral = "Neutral";
                public const string SHE = "SHE";
            }

            public static class SelectableFactions
            {
                public static readonly string[] All = [
                    Factions.SHE,
                ];
            }

            public record FactionMetadata(
                string Id,
                string ShortNameJa,
                string ShortNameEn,
                string FullNameJa,
                string FullNameEn,
                bool IsCollectible,
                int SortOrder
            );

            public static class FactionsMetadata
            {
                public static readonly FactionMetadata[] All = [
                    new FactionMetadata("Neutral", "Neutral", "Neutral", "Neutral", "Neutral", false, 0),
                    new FactionMetadata("SHE", "SHE", "SHE", "SHE Full", "SHE Full", true, 1),
                ];

                public static readonly System.Collections.Generic.Dictionary<string, FactionMetadata> ById =
                    System.Linq.Enumerable.ToDictionary(All, m => m.Id);
            }

            public static class Zones
            {
                public const string Frontend = "frontend";
                public const string Backend = "backend";
            }

            public static class Ranks
            {
                public const string Small = "small";
                public const string Medium = "medium";
            }

            public static class InstanceFamilies
            {
                public const string M = "M";
                public const string C = "C";
            }

            public static class RestrictionValues
            {
                public const string Forbidden = "forbidden";
                public const string Limited = "limited";
            }

            public static class MatchTypes
            {
                public const string Pvp = "pvp";
            }

            public static class StatTypes
            {
                public const string Tp = "tp";
            }

            public static class CardTypes
            {
                public const string Compute = "Compute";
                public const string Platform = "Platform";
            }

            public static class Subtypes
            {
                public static class Compute
                {
                    public const string VM = "VM";
                }
            }

            ''')
        assert got == expected


class TestGoldenTs:
    def test_ts_output_matches(self, tmp_path, monkeypatch, fixture_data, fixture_factions):
        monkeypatch.setattr(gen, "NPM_GAME_DESIGN_DIR", tmp_path)
        gen.generate_ts_game_design(fixture_data, fixture_factions)
        got = (tmp_path / "src" / "index.ts").read_text()
        expected = textwrap.dedent('''\
            // Code generated by scripts/generate_constants.py; DO NOT EDIT.

            export const ZONES = ["frontend", "backend"] as const;
            export type Zone = (typeof ZONES)[number];

            export const RANKS = ["small", "medium"] as const;
            export type Rank = (typeof RANKS)[number];

            export const INSTANCE_FAMILIES = ["M", "C"] as const;
            export type InstanceFamily = (typeof INSTANCE_FAMILIES)[number] | '';

            export const RESTRICTION_VALUES = ["forbidden", "limited"] as const;
            export type Restriction = (typeof RESTRICTION_VALUES)[number];

            export const MATCH_TYPES = ["pvp"] as const;
            export type MatchType = (typeof MATCH_TYPES)[number];

            export const STAT_TYPES = ["tp"] as const;
            export type StatType = (typeof STAT_TYPES)[number];

            export const CARD_TYPES = ["Compute", "Platform"] as const;
            export type CardType = (typeof CARD_TYPES)[number];

            export const COMPUTE_SUBTYPES = ["VM"] as const;
            export type ComputeSubtype = (typeof COMPUTE_SUBTYPES)[number];

            export const FACTIONS = ["Neutral", "SHE"] as const;
            export const SELECTABLE_FACTIONS = ["SHE"] as const;
            export type FactionId = (typeof SELECTABLE_FACTIONS)[number];

            export interface FactionMetadata {
              id: string;
              shortNameJa: string;
              shortNameEn: string;
              fullNameJa: string;
              fullNameEn: string;
              isCollectible: boolean;
              sortOrder: number;
            }

            export const FACTIONS_METADATA: readonly FactionMetadata[] = [
              {"id": "Neutral", "shortNameJa": "Neutral", "shortNameEn": "Neutral", "fullNameJa": "Neutral", "fullNameEn": "Neutral", "isCollectible": false, "sortOrder": 0},
              {"id": "SHE", "shortNameJa": "SHE", "shortNameEn": "SHE", "fullNameJa": "SHE Full", "fullNameEn": "SHE Full", "isCollectible": true, "sortOrder": 1},
            ];

            export const FACTION_BY_ID: Record<string, FactionMetadata> = {
              "Neutral": FACTIONS_METADATA[0],
              "SHE": FACTIONS_METADATA[1],
            };

            export const RESTRICTION_COPY_COUNT: Record<Restriction, number> = {
              forbidden: 0,
              limited: 1,
            };

            export const INITIAL_VALUES = {
              deckSize: 30,
            } as const;

            ''')
        assert got == expected


class TestValidate:
    """restriction_copy_count と restriction_values の整合性検証。"""

    def test_matches_ok(self):
        """観点: 全 restriction 値が copy_count にマップされていれば例外なし。"""
        gen._validate({
            "restriction_values": ["forbidden", "limited", "unlimited"],
            "restriction_copy_count": {"forbidden": 0, "limited": 1, "unlimited": 3},
        })

    def test_missing_key_raises(self):
        """観点: copy_count に未マップの restriction 値があれば ValueError。

        silent に 0 や undefined を返さず、SSoT 違反として早期検出する。
        """
        with pytest.raises(ValueError, match="missing.*unlimited"):
            gen._validate({
                "restriction_values": ["forbidden", "limited", "unlimited"],
                "restriction_copy_count": {"forbidden": 0, "limited": 1},
            })

    def test_extra_key_raises(self):
        """観点: copy_count に restriction_values 外のキーがあれば ValueError。

        typo や削除漏れによる SSoT 不整合を防ぐ。
        """
        with pytest.raises(ValueError, match="extra.*ghost"):
            gen._validate({
                "restriction_values": ["forbidden", "limited"],
                "restriction_copy_count": {"forbidden": 0, "limited": 1, "ghost": 9},
            })


class TestToPascal:
    @pytest.mark.parametrize(
        ("value", "expected"),
        [
            ("AI/ML", "AIML"),
            ("", ""),
            ("frontend", "Frontend"),
            ("Compute", "Compute"),
            ("instance_family", "InstanceFamily"),
            ("semi-limited", "SemiLimited"),
        ],
    )
    def test_to_pascal(self, value, expected):
        assert gen.convert_to_pascal(value) == expected
