"""generate_constants.py のユニットテスト。"""

import textwrap

import pytest
import yaml

import generate_constants as gen


# ─── Golden fixture ─────────────────────────────────────
# 固定の小さな入力で 3 言語の出力を完全一致検証する。出力仕様
# (フィールド順・特殊ルール "instance_families の空文字 union" など) が
# 意図せず変わった場合に即座に壊れる。

@pytest.fixture
def fixture_data():
    return {
        "zones": ["frontend", "backend"],
        "ranks": ["small", "medium"],
        "instance_families": ["M", "C"],
        "restriction_values": ["forbidden", "limited"],
        "restriction_copy_count": {"forbidden": 0, "limited": 1},
        "match_types": ["pvp"],
        "stat_types": ["tp"],
        "card_types": ["Compute", "Platform"],
        "subtypes": {
            "Compute": ["VM"],
        },
        "initial_values": {"deck_size": 30},
        "game_rules": {"hand_limit": 6, "slots_per_zone": 3},
        "rank_multipliers": {"small": 1, "medium": 2},
        "family_multipliers": {
            "M": {"stat": 1.0, "av": 1.0},
            "C": {"stat": 1.3, "av": 0.7},
        },
    }


@pytest.fixture
def fixture_factions():
    return [
        {
            "id": "SHE",
            "short_name_ja": "SHE",
            "short_name_en": "SHE",
            "full_name_ja": "SHE Full",
            "full_name_en": "SHE Full",
            "is_collectible": True,
            "sort_order": 1,
        },
        {
            "id": "Neutral",
            "short_name_ja": "Neutral",
            "short_name_en": "Neutral",
            "full_name_ja": "Neutral",
            "full_name_en": "Neutral",
            "is_collectible": False,
            "sort_order": 0,
        },
    ]


@pytest.fixture
def real_ssot():
    game_design = yaml.safe_load(gen.GAME_DESIGN_YAML.read_text(encoding="utf-8"))
    factions = yaml.safe_load(gen.FACTIONS_YAML.read_text(encoding="utf-8"))["factions"]
    return game_design, factions


@pytest.fixture
def generated_outputs(tmp_path, monkeypatch, fixture_data, fixture_factions):
    monkeypatch.setattr(gen, "GO_GAME_DESIGN_DIR", tmp_path / "go")
    monkeypatch.setattr(gen, "DOTNET_GAME_DESIGN_DIR", tmp_path / "dotnet")
    monkeypatch.setattr(gen, "NPM_GAME_DESIGN_DIR", tmp_path / "npm")
    gen.generate_go_game_design(fixture_data, fixture_factions)
    gen.generate_csharp_game_design(fixture_data, fixture_factions)
    gen.generate_ts_game_design(fixture_data, fixture_factions)
    return {
        "go": (tmp_path / "go" / "constants_gen.go").read_text(encoding="utf-8"),
        "cs": (tmp_path / "dotnet" / "GameDesignConstants_gen.cs").read_text(encoding="utf-8"),
        "ts": (tmp_path / "npm" / "src" / "index.ts").read_text(encoding="utf-8"),
    }


def _stripped_lines(text):
    """生成テキストを行ごとに前後空白を除いたリストに変換します。"""
    return [line.strip() for line in text.splitlines()]


def _block_line_set(text, opening, closing):
    """開始行と終了行に挟まれたブロックの中身を、行ごとの集合として抽出します。"""
    lines = _stripped_lines(text)
    start = lines.index(opening) + 1
    end = lines.index(closing, start)
    return set(lines[start:end])


class TestGoの生成結果:
    def test_固定入力がGoの期待出力と完全一致する(self, tmp_path, monkeypatch, fixture_data, fixture_factions):
        monkeypatch.setattr(gen, "GO_GAME_DESIGN_DIR", tmp_path)
        gen.generate_go_game_design(fixture_data, fixture_factions)
        got = (tmp_path / "constants_gen.go").read_text()
        expected = textwrap.dedent('''\
            // Code generated by scripts/generate_constants.py; DO NOT EDIT.

            package game_design

            // Initial values.
            const (
            \tDeckSize = 30
            )

            // Factions.
            const (
            \tFactionNeutral = "Neutral"
            \tFactionSHE = "SHE"
            )

            // SelectableFactions is the list of factions players can choose.
            var SelectableFactions = []string{
            \tFactionSHE,
            }

            // FactionMetadata holds display and ordering information for a faction.
            type FactionMetadata struct {
            \tID            string
            \tShortNameJa   string
            \tShortNameEn   string
            \tFullNameJa    string
            \tFullNameEn    string
            \tIsCollectible bool
            \tSortOrder     int
            }

            // FactionsMetadata lists all factions in sort order.
            var FactionsMetadata = []FactionMetadata{
            \t{
            \t\tID:            "Neutral",
            \t\tShortNameJa:   "Neutral",
            \t\tShortNameEn:   "Neutral",
            \t\tFullNameJa:    "Neutral",
            \t\tFullNameEn:    "Neutral",
            \t\tIsCollectible: false,
            \t\tSortOrder:     0,
            \t},
            \t{
            \t\tID:            "SHE",
            \t\tShortNameJa:   "SHE",
            \t\tShortNameEn:   "SHE",
            \t\tFullNameJa:    "SHE Full",
            \t\tFullNameEn:    "SHE Full",
            \t\tIsCollectible: true,
            \t\tSortOrder:     1,
            \t},
            }

            // FactionByID looks up faction metadata by ID.
            var FactionByID = map[string]FactionMetadata{
            \t"Neutral": FactionsMetadata[0],
            \t"SHE": FactionsMetadata[1],
            }

            // Zones.
            const (
            \tZoneFrontend = "frontend"
            \tZoneBackend = "backend"
            )

            // Ranks.
            const (
            \tRankSmall = "small"
            \tRankMedium = "medium"
            )

            // Instance families.
            const (
            \tInstanceFamilyM = "M"
            \tInstanceFamilyC = "C"
            )

            // Restriction values.
            const (
            \tRestrictionForbidden = "forbidden"
            \tRestrictionLimited = "limited"
            )

            // Match types.
            const (
            \tMatchTypePvp = "pvp"
            )

            // Stat types.
            const (
            \tStatTypeTp = "tp"
            )

            // Card types.
            const (
            \tCardTypeCompute = "Compute"
            \tCardTypePlatform = "Platform"
            )

            // Card subtypes (Compute).
            const (
            \tSubtypeComputeVM = "VM"
            )

            // RestrictionCopyCount returns the deck investment cap per restriction value.
            var RestrictionCopyCount = map[string]int{
            \tRestrictionForbidden: 0,
            \tRestrictionLimited: 1,
            }

            // Game rules.
            const (
            \tGameRuleHandLimit = 6
            \tGameRuleSlotsPerZone = 3
            )

            // RankMultipliers maps rank to its stat multiplier.
            var RankMultipliers = map[string]int{
            \tRankSmall: 1,
            \tRankMedium: 2,
            }

            // FamilyMultiplier holds the stat and availability multipliers for an instance family.
            type FamilyMultiplier struct {
            \tStat float64
            \tAv   float64
            }

            // FamilyMultipliers maps instance family to its multipliers.
            var FamilyMultipliers = map[string]FamilyMultiplier{
            \tInstanceFamilyM: {Stat: 1.0, Av: 1.0},
            \tInstanceFamilyC: {Stat: 1.3, Av: 0.7},
            }

            ''')
        assert got == expected


class TestCSharpの生成結果:
    def test_固定入力がCSharpの期待出力と完全一致する(self, tmp_path, monkeypatch, fixture_data, fixture_factions):
        monkeypatch.setattr(gen, "DOTNET_GAME_DESIGN_DIR", tmp_path)
        gen.generate_csharp_game_design(fixture_data, fixture_factions)
        got = (tmp_path / "GameDesignConstants_gen.cs").read_text()
        expected = textwrap.dedent('''\
            // Code generated by scripts/generate_constants.py; DO NOT EDIT.

            namespace OverloadParty.GameDesignConstants;

            public static class InitialValues
            {
                public const int DeckSize = 30;
            }

            public static class Factions
            {
                public const string Neutral = "Neutral";
                public const string SHE = "SHE";
            }

            public static class SelectableFactions
            {
                public static readonly string[] All = [
                    Factions.SHE,
                ];
            }

            public record FactionMetadata(
                string Id,
                string ShortNameJa,
                string ShortNameEn,
                string FullNameJa,
                string FullNameEn,
                bool IsCollectible,
                int SortOrder
            );

            public static class FactionsMetadata
            {
                public static readonly FactionMetadata[] All = [
                    new FactionMetadata("Neutral", "Neutral", "Neutral", "Neutral", "Neutral", false, 0),
                    new FactionMetadata("SHE", "SHE", "SHE", "SHE Full", "SHE Full", true, 1),
                ];

                public static readonly System.Collections.Generic.Dictionary<string, FactionMetadata> ById =
                    System.Linq.Enumerable.ToDictionary(All, m => m.Id);
            }

            public static class Zones
            {
                public const string Frontend = "frontend";
                public const string Backend = "backend";
            }

            public static class Ranks
            {
                public const string Small = "small";
                public const string Medium = "medium";
            }

            public static class InstanceFamilies
            {
                public const string M = "M";
                public const string C = "C";
            }

            public static class RestrictionValues
            {
                public const string Forbidden = "forbidden";
                public const string Limited = "limited";
            }

            public static class MatchTypes
            {
                public const string Pvp = "pvp";
            }

            public static class StatTypes
            {
                public const string Tp = "tp";
            }

            public static class CardTypes
            {
                public const string Compute = "Compute";
                public const string Platform = "Platform";
            }

            public static class Subtypes
            {
                public static class Compute
                {
                    public const string VM = "VM";
                }
            }

            public static class GameRules
            {
                public const int HandLimit = 6;
                public const int SlotsPerZone = 3;
            }

            public static class RankMultipliers
            {
                public const long Small = 1;
                public const long Medium = 2;
            }

            public static class FamilyMultipliers
            {
                public const double MStat = 1.0;
                public const double MAv = 1.0;
                public const double CStat = 1.3;
                public const double CAv = 0.7;
            }

            ''')
        assert got == expected


class TestTypeScriptの生成結果:
    def test_固定入力がTypeScriptの期待出力と完全一致する(self, tmp_path, monkeypatch, fixture_data, fixture_factions):
        monkeypatch.setattr(gen, "NPM_GAME_DESIGN_DIR", tmp_path)
        gen.generate_ts_game_design(fixture_data, fixture_factions)
        got = (tmp_path / "src" / "index.ts").read_text()
        expected = textwrap.dedent('''\
            // Code generated by scripts/generate_constants.py; DO NOT EDIT.

            export const ZONES = ["frontend", "backend"] as const;
            export type Zone = (typeof ZONES)[number];

            export const RANKS = ["small", "medium"] as const;
            export type Rank = (typeof RANKS)[number];

            export const INSTANCE_FAMILIES = ["M", "C"] as const;
            export type InstanceFamily = (typeof INSTANCE_FAMILIES)[number] | '';

            export const RESTRICTION_VALUES = ["forbidden", "limited"] as const;
            export type Restriction = (typeof RESTRICTION_VALUES)[number];

            export const MATCH_TYPES = ["pvp"] as const;
            export type MatchType = (typeof MATCH_TYPES)[number];

            export const STAT_TYPES = ["tp"] as const;
            export type StatType = (typeof STAT_TYPES)[number];

            export const CARD_TYPES = ["Compute", "Platform"] as const;
            export type CardType = (typeof CARD_TYPES)[number];

            export const COMPUTE_SUBTYPES = ["VM"] as const;
            export type ComputeSubtype = (typeof COMPUTE_SUBTYPES)[number];

            export const FACTIONS = ["Neutral", "SHE"] as const;
            export const SELECTABLE_FACTIONS = ["SHE"] as const;
            export type FactionId = (typeof SELECTABLE_FACTIONS)[number];

            export interface FactionMetadata {
              id: string;
              shortNameJa: string;
              shortNameEn: string;
              fullNameJa: string;
              fullNameEn: string;
              isCollectible: boolean;
              sortOrder: number;
            }

            export const FACTIONS_METADATA: readonly FactionMetadata[] = [
              {"id": "Neutral", "shortNameJa": "Neutral", "shortNameEn": "Neutral", "fullNameJa": "Neutral", "fullNameEn": "Neutral", "isCollectible": false, "sortOrder": 0},
              {"id": "SHE", "shortNameJa": "SHE", "shortNameEn": "SHE", "fullNameJa": "SHE Full", "fullNameEn": "SHE Full", "isCollectible": true, "sortOrder": 1},
            ];

            export const FACTION_BY_ID: Record<string, FactionMetadata> = {
              "Neutral": FACTIONS_METADATA[0],
              "SHE": FACTIONS_METADATA[1],
            };

            export const RESTRICTION_COPY_COUNT: Record<Restriction, number> = {
              forbidden: 0,
              limited: 1,
            };

            export const INITIAL_VALUES = {
              deckSize: 30,
            } as const;

            export const GAME_RULES = {
              handLimit: 6,
              slotsPerZone: 3,
            } as const;

            export const RANK_MULTIPLIERS: Record<Rank, number> = {
              small: 1,
              medium: 2,
            };

            export interface FamilyMultiplier {
              stat: number;
              av: number;
            }

            export const FAMILY_MULTIPLIERS: Record<(typeof INSTANCE_FAMILIES)[number], FamilyMultiplier> = {
              M: { stat: 1.0, av: 1.0 },
              C: { stat: 1.3, av: 0.7 },
            };

            ''')
        assert got == expected


class Test実SSoTからの生成:
    @pytest.mark.parametrize(
        ("generate", "dir_attr", "output_relpath", "committed_relpath"),
        [
            pytest.param(
                gen.generate_go_game_design,
                "GO_GAME_DESIGN_DIR",
                "constants_gen.go",
                "packages/game-design-constants/constants_gen.go",
                id="Go言語のとき、実SSoTから生成した結果がコミット済みconstants_gen.goと一致する",
            ),
            pytest.param(
                gen.generate_csharp_game_design,
                "DOTNET_GAME_DESIGN_DIR",
                "GameDesignConstants_gen.cs",
                "packages/game-design-constants-dotnet/GameDesignConstants_gen.cs",
                id="CSharp言語のとき、実SSoTから生成した結果がコミット済みGameDesignConstants_gen.csと一致する",
            ),
            pytest.param(
                gen.generate_ts_game_design,
                "NPM_GAME_DESIGN_DIR",
                "src/index.ts",
                "packages/game-design-constants-npm/src/index.ts",
                id="TypeScript言語のとき、実SSoTから生成した結果がコミット済みindex.tsと一致する",
            ),
        ],
    )
    def test_実SSoTから生成する(self, tmp_path, monkeypatch, real_ssot, generate, dir_attr, output_relpath, committed_relpath):
        game_design, factions = real_ssot
        monkeypatch.setattr(gen, dir_attr, tmp_path)
        generate(game_design, factions)

        got = (tmp_path / output_relpath).read_text(encoding="utf-8")
        committed = (gen.ROOT / committed_relpath).read_text(encoding="utf-8")
        assert got == committed


class Test生成の冪等性:
    @pytest.mark.parametrize(
        ("generate", "dir_attr", "output_relpath"),
        [
            pytest.param(gen.generate_go_game_design, "GO_GAME_DESIGN_DIR", "constants_gen.go", id="Go言語のとき、実SSoTから2回生成しても出力が同一になる"),
            pytest.param(gen.generate_csharp_game_design, "DOTNET_GAME_DESIGN_DIR", "GameDesignConstants_gen.cs", id="CSharp言語のとき、実SSoTから2回生成しても出力が同一になる"),
            pytest.param(gen.generate_ts_game_design, "NPM_GAME_DESIGN_DIR", "src/index.ts", id="TypeScript言語のとき、実SSoTから2回生成しても出力が同一になる"),
        ],
    )
    def test_実SSoTから2回生成する(self, tmp_path, monkeypatch, real_ssot, generate, dir_attr, output_relpath):
        game_design, factions = real_ssot

        monkeypatch.setattr(gen, dir_attr, tmp_path / "run1")
        generate(game_design, factions)

        monkeypatch.setattr(gen, dir_attr, tmp_path / "run2")
        generate(game_design, factions)

        first = (tmp_path / "run1" / output_relpath).read_text(encoding="utf-8")
        second = (tmp_path / "run2" / output_relpath).read_text(encoding="utf-8")
        assert first == second


class TestSSoTにキーが欠けているときの停止:
    @pytest.mark.parametrize(
        ("generate", "dir_attr"),
        [
            pytest.param(gen.generate_go_game_design, "GO_GAME_DESIGN_DIR", id="Goの生成が欠けたキーを示して停止する"),
            pytest.param(gen.generate_csharp_game_design, "DOTNET_GAME_DESIGN_DIR", id="CSharpの生成が欠けたキーを示して停止する"),
            pytest.param(gen.generate_ts_game_design, "NPM_GAME_DESIGN_DIR", id="TypeScriptの生成が欠けたキーを示して停止する"),
        ],
    )
    @pytest.mark.parametrize(
        "missing_key",
        [
            pytest.param("zones", id="zones が欠けているとき"),
            pytest.param("ranks", id="ranks が欠けているとき"),
            pytest.param("instance_families", id="instance_families が欠けているとき"),
            pytest.param("restriction_values", id="restriction_values が欠けているとき"),
            pytest.param("match_types", id="match_types が欠けているとき"),
            pytest.param("stat_types", id="stat_types が欠けているとき"),
            pytest.param("subtypes", id="subtypes が欠けているとき"),
        ],
    )
    def test_キーの欠けたSSoTから生成する(
        self, tmp_path, monkeypatch, fixture_data, fixture_factions, missing_key, generate, dir_attr
    ):
        del fixture_data[missing_key]
        monkeypatch.setattr(gen, dir_attr, tmp_path)

        with pytest.raises(KeyError, match=missing_key):
            generate(fixture_data, fixture_factions)


class Test生成物への陣営一覧の反映:
    def test_is_collectibleの真偽に関わらず全陣営がGoのFaction定数に現れる(self, generated_outputs):
        lines = _stripped_lines(generated_outputs["go"])
        assert 'FactionNeutral = "Neutral"' in lines
        assert 'FactionSHE = "SHE"' in lines

    def test_is_collectibleの真偽に関わらず全陣営がCSharpのFactions定数に現れる(self, generated_outputs):
        lines = _stripped_lines(generated_outputs["cs"])
        assert 'public const string Neutral = "Neutral";' in lines
        assert 'public const string SHE = "SHE";' in lines

    def test_is_collectibleの真偽に関わらず全陣営がTSのFACTIONS配列に現れる(self, generated_outputs):
        lines = _stripped_lines(generated_outputs["ts"])
        assert 'export const FACTIONS = ["Neutral", "SHE"] as const;' in lines


class Test選択可能な陣営の絞り込み:
    def test_is_collectibleが偽の陣営を含むときGoのSelectableFactionsにはis_collectibleが真の陣営だけが現れる(self, generated_outputs):
        lines = _stripped_lines(generated_outputs["go"])
        assert "FactionSHE," in lines
        assert "FactionNeutral," not in lines

    def test_is_collectibleが偽の陣営を含むときCSharpのSelectableFactionsにはis_collectibleが真の陣営だけが現れる(self, generated_outputs):
        lines = _stripped_lines(generated_outputs["cs"])
        assert "Factions.SHE," in lines
        assert "Factions.Neutral," not in lines

    def test_is_collectibleが偽の陣営を含むときTSのSELECTABLE_FACTIONSにはis_collectibleが真の陣営だけが現れる(self, generated_outputs):
        lines = _stripped_lines(generated_outputs["ts"])
        assert 'export const SELECTABLE_FACTIONS = ["SHE"] as const;' in lines


class TestIDから陣営を引く表の生成:
    def test_is_collectibleが偽の陣営を含むときも全陣営がGoのFactionByIDに現れる(self, generated_outputs):
        lines = _stripped_lines(generated_outputs["go"])
        assert '"Neutral": FactionsMetadata[0],' in lines
        assert '"SHE": FactionsMetadata[1],' in lines

    def test_is_collectibleが偽の陣営を含むときも全陣営がTSのFACTION_BY_IDに現れる(self, generated_outputs):
        lines = _stripped_lines(generated_outputs["ts"])
        assert '"Neutral": FACTIONS_METADATA[0],' in lines
        assert '"SHE": FACTIONS_METADATA[1],' in lines


class TestインスタンスファミリのTypeScript型の生成:
    def test_InstanceFamily型は空文字を許容するunionになる(self, generated_outputs):
        lines = _stripped_lines(generated_outputs["ts"])
        assert "export type InstanceFamily = (typeof INSTANCE_FAMILIES)[number] | '';" in lines

    @pytest.mark.parametrize(
        "type_declaration_line",
        [
            pytest.param("export type Zone = (typeof ZONES)[number];", id="Zone型のとき、空文字を含まないunionになる"),
            pytest.param("export type Rank = (typeof RANKS)[number];", id="Rank型のとき、空文字を含まないunionになる"),
            pytest.param("export type Restriction = (typeof RESTRICTION_VALUES)[number];", id="Restriction型のとき、空文字を含まないunionになる"),
            pytest.param("export type MatchType = (typeof MATCH_TYPES)[number];", id="MatchType型のとき、空文字を含まないunionになる"),
            pytest.param("export type StatType = (typeof STAT_TYPES)[number];", id="StatType型のとき、空文字を含まないunionになる"),
        ],
    )
    def test_InstanceFamily以外の型は空文字を含まないunionになる(self, generated_outputs, type_declaration_line):
        lines = _stripped_lines(generated_outputs["ts"])
        assert type_declaration_line in lines


class TestRestrictionCopyCountのキー集合がrestriction_valuesと一致する:
    def test_GoのRestrictionCopyCountのキー集合がrestriction_valuesと一致する(self, generated_outputs):
        block = _block_line_set(
            generated_outputs["go"],
            "var RestrictionCopyCount = map[string]int{",
            "}",
        )
        assert block == {"RestrictionForbidden: 0,", "RestrictionLimited: 1,"}

    def test_TSのRESTRICTION_COPY_COUNTのキー集合がrestriction_valuesと一致する(self, generated_outputs):
        block = _block_line_set(
            generated_outputs["ts"],
            "export const RESTRICTION_COPY_COUNT: Record<Restriction, number> = {",
            "};",
        )
        assert block == {"forbidden: 0,", "limited: 1,"}


class Testキー集合整合性の検証:
    def test_宣言値の集合とマッピングのキー集合が一致していれば例外なし(self):
        gen._validate_key_set_matches(
            "copy_count", {"a": 0, "b": 1, "c": 3}, "values", ["a", "b", "c"]
        )

    def test_マッピングに未マップの宣言値があればValueError(self):
        # silent に 0 や undefined を返さず、SSoT 違反として早期検出する。
        with pytest.raises(ValueError, match="missing.*c"):
            gen._validate_key_set_matches(
                "copy_count", {"a": 0, "b": 1}, "values", ["a", "b", "c"]
            )

    def test_マッピングに宣言値外のキーがあればValueError(self):
        # typo や削除漏れによる SSoT 不整合を防ぐ。
        with pytest.raises(ValueError, match="extra.*ghost"):
            gen._validate_key_set_matches(
                "copy_count", {"a": 0, "b": 1, "ghost": 9}, "values", ["a", "b"]
            )

    def test_不足と余剰が同時にあればValueErrorに両方の内容を含む(self):
        with pytest.raises(ValueError, match=r"missing.*b.*extra.*ghost"):
            gen._validate_key_set_matches(
                "copy_count", {"a": 0, "ghost": 9}, "values", ["a", "b"]
            )


class Test全体検証の配線:
    def test_restriction_rankmultiplier_familymultiplierの全整合性が取れていれば例外なし(self):
        gen._validate({
            "restriction_values": ["forbidden", "limited"],
            "restriction_copy_count": {"forbidden": 0, "limited": 1},
            "ranks": ["small", "medium"],
            "rank_multipliers": {"small": 1, "medium": 2},
            "instance_families": ["M", "C"],
            "family_multipliers": {
                "M": {"stat": 1.0, "av": 1.0},
                "C": {"stat": 1.3, "av": 0.7},
            },
        })

    def test_rank_multipliersがranksと不整合のときValueError(self):
        with pytest.raises(ValueError, match="rank_multipliers keys must match ranks"):
            gen._validate({
                "restriction_values": ["forbidden", "limited"],
                "restriction_copy_count": {"forbidden": 0, "limited": 1},
                "ranks": ["small", "medium"],
                "rank_multipliers": {"small": 1},
                "instance_families": ["M", "C"],
                "family_multipliers": {
                    "M": {"stat": 1.0, "av": 1.0},
                    "C": {"stat": 1.3, "av": 0.7},
                },
            })

    def test_family_multipliersがinstance_familiesと不整合のときValueError(self):
        with pytest.raises(ValueError, match="family_multipliers keys must match instance_families"):
            gen._validate({
                "restriction_values": ["forbidden", "limited"],
                "restriction_copy_count": {"forbidden": 0, "limited": 1},
                "ranks": ["small", "medium"],
                "rank_multipliers": {"small": 1, "medium": 2},
                "instance_families": ["M", "C"],
                "family_multipliers": {"M": {"stat": 1.0, "av": 1.0}},
            })

    def test_不足と余剰が同時にあればValueErrorに両方の内容を含む(self):
        with pytest.raises(ValueError, match=r"missing.*limited.*extra.*ghost"):
            gen._validate({
                "restriction_values": ["forbidden", "limited"],
                "restriction_copy_count": {"forbidden": 0, "ghost": 9},
            })


class TestPascalCaseへの変換:
    @pytest.mark.parametrize(
        ("value", "expected"),
        [
            pytest.param("AI/ML", "AIML", id="スラッシュ区切りの AI/ML は AIML になる"),
            pytest.param("", "", id="空文字は空文字になる"),
            pytest.param("frontend", "Frontend", id="frontend は Frontend になる"),
            pytest.param("Compute", "Compute", id="既に PascalCase の Compute はそのまま"),
            pytest.param("instance_family", "InstanceFamily", id="スネークケースの instance_family は InstanceFamily になる"),
            pytest.param("semi-limited", "SemiLimited", id="ハイフン区切りの semi-limited は SemiLimited になる"),
        ],
    )
    def test_文字列をPascalCaseに変換する(self, value, expected):
        assert gen.convert_to_pascal(value) == expected


class TestCamelCaseへの変換:
    @pytest.mark.parametrize(
        ("key", "expected"),
        [
            pytest.param("deck_size", "deckSize", id="スネークケースの deck_size は deckSize になる"),
            pytest.param("launch_failure_turn", "launchFailureTurn", id="複数アンダースコアの launch_failure_turn は launchFailureTurn になる"),
            pytest.param("maxturns", "maxturns", id="アンダースコアが無い maxturns はそのまま"),
            pytest.param("", "", id="空文字は空文字になる"),
        ],
    )
    def test_文字列をcamelCaseに変換する(self, key, expected):
        assert gen.convert_to_camel(key) == expected


class TestScreamingSnakeCaseへの変換:
    @pytest.mark.parametrize(
        ("value", "expected"),
        [
            pytest.param("AI/ML", "AIML", id="スラッシュ区切りの AI/ML は AIML になる"),
            pytest.param("semi-limited", "SEMI_LIMITED", id="ハイフン区切りの semi-limited は SEMI_LIMITED になる"),
            pytest.param("instance_family", "INSTANCE_FAMILY", id="スネークケースの instance_family は INSTANCE_FAMILY になる"),
            pytest.param("DataResource", "DATARESOURCE", id="パスカルケースの DataResource は DATARESOURCE になる"),
            pytest.param("", "", id="空文字は空文字になる"),
        ],
    )
    def test_文字列をSCREAMING_SNAKE_CASEに変換する(self, value, expected):
        assert gen.convert_to_screaming_snake(value) == expected
