// Code generated by scripts/generate_constants.py; DO NOT EDIT.

export const PHASES = ["draw", "main", "battle", "end"] as const;
export type GamePhase = (typeof PHASES)[number] | 'selecting';

export const ZONES = ["frontend", "backend", "support"] as const;
export type Zone = (typeof ZONES)[number];

export const RANKS = ["small", "medium", "large"] as const;
export type Rank = (typeof RANKS)[number];

export const INSTANCE_FAMILIES = ["M", "C", "R"] as const;
export type InstanceFamily = (typeof INSTANCE_FAMILIES)[number] | '';

export const FACTIONS = ["SHE", "Tenki", "Sugar", "Tuners", "Neutral"] as const;
export const SELECTABLE_FACTIONS = ["SHE", "Tenki", "Sugar", "Tuners"] as const;
export type FactionId = (typeof SELECTABLE_FACTIONS)[number];
export const FACTION_DISPLAY_NAMES: Record<string, string> = { "SHE": "SHE（Smile Horizon Express）", "Tenki": "天気使い", "Sugar": "しゅがーらぼ", "Tuners": "調律部（チューナーズ）", "Neutral": "Neutral" };

export const GAME_STATUS = ["waiting", "playing", "finished"] as const;
export type GameStatus = (typeof GAME_STATUS)[number];

export const WIN_REASONS = ["budget_zero", "system_down", "repository_out", "timeout", "disconnect", "turn_limit", "draw", "launch_failure"] as const;
export type WinReason = (typeof WIN_REASONS)[number];

export const ACTION_TYPES = ["play_card", "attack", "scale_up", "monetize", "discard_hand", "use_effect", "set_reactive", "migrate", "end_phase", "forfeit"] as const;
export type GameActionType = (typeof ACTION_TYPES)[number];

export const EVENT_TYPES = ["play_card", "attach_card", "attack", "scale_up", "monetize", "discard_hand", "use_effect", "reactive_revealed", "migrate", "migration_complete", "phase_change", "phase_end", "turn_end", "turn_start", "game_over"] as const;
export type EventType = (typeof EVENT_TYPES)[number];

export const CARD_TYPES = ["Compute", "Container", "Orchestrator", "Serverless", "AI/ML", "Database", "ObjectStorage", "CacheDB", "Platform", "Attachment", "Strategy", "Reactive", "Incident"] as const;
export type CardType = (typeof CARD_TYPES)[number];

const COMPUTE_TYPES: ReadonlySet<string> = new Set(["Compute", "Container", "Orchestrator", "Serverless", "AI/ML"]);
const DATA_TYPES: ReadonlySet<string> = new Set(["Database", "ObjectStorage", "CacheDB"]);

/** Returns true if the card type is a deployable resource (compute, AI/ML, or data). */
export function isResourceType(cardType: string): boolean {
  return COMPUTE_TYPES.has(cardType) || DATA_TYPES.has(cardType);
}

/** Returns true if the card can be placed in the frontend zone. */
export function isFrontendEligible(cardType: string): boolean {
  return COMPUTE_TYPES.has(cardType) || cardType === 'ObjectStorage';
}

/** Returns true if the card can be placed in the backend zone. */
export function isBackendEligible(cardType: string): boolean {
  return DATA_TYPES.has(cardType) || COMPUTE_TYPES.has(cardType);
}

/** Returns true if the card goes in the support zone (Platform, Strategy, Incident, Reactive). */
export function isSupportType(cardType: string): boolean {
  return cardType === 'Platform' || cardType === 'Strategy' || cardType === 'Reactive' || cardType === 'Incident';
}

/** Returns true if the card is an Attachment (attaches to resources, not support zone). */
export function isAttachmentType(cardType: string): boolean {
  return cardType === 'Attachment';
}

export const WS_SERVER_MSG_TYPES = ["game_state", "game_over", "error", "game_entered", "matchmaking_started", "matchmaking_cancelled", "action_rejected", "stamp_used", "pong", "match_found", "action_performed", "turn_controls", "npc_battle_created"] as const;
export type WSServerMsgType = (typeof WS_SERVER_MSG_TYPES)[number];
export const WS_CLIENT_MSG_TYPES = ["game_enter", "matchmaking_start", "matchmaking_cancel", "game_action", "use_stamp", "ping", "npc_battle_start"] as const;
export type WSClientMsgType = (typeof WS_CLIENT_MSG_TYPES)[number];

export const EFFECT_DURATIONS = ["this_turn", "until_next_turn_end", "until_next_own_turn_end"] as const;
export type EffectDuration = (typeof EFFECT_DURATIONS)[number];

export const RESTRICTION_VALUES = ["unlimited", "limited", "semi_limited", "forbidden"] as const;
export type Restriction = (typeof RESTRICTION_VALUES)[number];

/** Returns the maximum number of copies allowed in a deck for a given restriction. */
export function restrictionCopyCount(restriction: Restriction): number {
  switch (restriction) {
    case 'forbidden': return 0;
    case 'limited': return 1;
    case 'semi_limited': return 2;
    case 'unlimited': return 3;
    default: return 3;
  }
}

export const INITIAL_VALUES = {
  budget: 5000,
  insightPool: 0,
  handSize: 5,
  handLimit: 6,
  timeBank: 480,
  deckSize: 30,
  maxAttachments: 2,
  slotsPerZone: 3,
} as const;

export const LEVEL = {
  expFormula: '60 * n^2',
  expWin: 40,
  expLoss: 20,
  expDraw: 30,
} as const;

