// Code generated by generate_from_yaml.py from data/event_schemas.json; DO NOT EDIT.

export interface PlayCardEventData {
  cardId: number;
  zone: string;
  index: number;
  cancelled?: boolean;
}

export interface AttachCardEventData {
  cardId: number;
  targetId: string;
}

export interface AttackEventData {
  attackerId: string;
  targetId: string;
  damage: number;
  destroyed: boolean;
  slaPenalty?: number;
  cancelled?: boolean;
}

export interface ScaleUpEventData {
  instanceId: string;
  targetRank: string;
  instanceFamily?: string;
}

export interface MonetizeEventData {
  totalAmount: number;
}

export interface DiscardHandEventData {
  discardedCount: number;
  discardedIds: string[];
}

export interface ActivateEffectEventData {
  cardNo: number;
  sourceId: string;
  targetId?: string;
}

export interface MigrateEventData {
  sourceInstanceId: string;
  targetInstanceId: string;
  sourceCardId: number;
  targetCardId: number;
}

export interface PhaseChangeEventData {
  previousPhase: string;
  currentPhase: string;
}

export interface PhaseEndEventData {
  phase: string;
  needsDiscard: boolean;
}

export interface TurnEndEventData {
  phase: string;
  nextTurn: number;
  activePlayer: number;
  currentPhase: string;
}

export interface TurnStartEventData {
  turn: number;
  activePlayer: number;
}

export interface EventDataMap {
  play_card: PlayCardEventData;
  attach_card: AttachCardEventData;
  attack: AttackEventData;
  scale_up: ScaleUpEventData;
  monetize: MonetizeEventData;
  discard_hand: DiscardHandEventData;
  activate_effect: ActivateEffectEventData;
  migrate: MigrateEventData;
  phase_change: PhaseChangeEventData;
  phase_end: PhaseEndEventData;
  turn_end: TurnEndEventData;
  turn_start: TurnStartEventData;
}
