// Code generated by scripts/generate_constants.py; DO NOT EDIT.

import type { InstanceFamily, Rank } from './constants';

/** Available action that a player can perform during their turn. */
export type AvailableAction =
  | { type: 'play_card'; hand_instance_id: string; card_id: string; valid_zones?: string[]; valid_targets?: string[]; cost?: number; choice_options?: string[] }
  | { type: 'attack'; source_instance_id: string; valid_targets: string[] }
  | { type: 'scale_up'; source_instance_id: string; target_rank: Rank; instance_family?: InstanceFamily; needs_family: boolean }
  | { type: 'monetize'; source_instance_id: string; remaining_capacity: number }
  | { type: 'use_effect'; source_instance_id: string; valid_targets?: string[]; effect_target_type: string; required_count: number };

