// Code generated by scripts/generate_constants.py; DO NOT EDIT.

namespace OverloadParty.GameData.Ws;

public static class WSServerMsgTypes
{
    public const string GameState = "game_state";
    public const string GameOver = "game_over";
    public const string Error = "error";
    public const string GameEntered = "game_entered";
    public const string MatchmakingStarted = "matchmaking_started";
    public const string MatchmakingCancelled = "matchmaking_cancelled";
    public const string ActionRejected = "action_rejected";
    public const string StampUsed = "stamp_used";
    public const string Pong = "pong";
    public const string MatchFound = "match_found";
    public const string ActionPerformed = "action_performed";
    public const string TurnControls = "turn_controls";
    public const string NpcBattleCreated = "npc_battle_created";
    public const string OpponentDisconnected = "opponent_disconnected";
    public const string OpponentReconnected = "opponent_reconnected";
    public const string SpectateJoined = "spectate_joined";
    public const string SpectateError = "spectate_error";
    public const string SpectateUpdate = "spectate_update";
    public const string SpectateEnded = "spectate_ended";
    public const string SpectateStampBroadcast = "spectate_stamp_broadcast";
    public const string GameStateRestore = "game_state_restore";
}

public static class WSClientMsgTypes
{
    public const string GameEnter = "game_enter";
    public const string MatchmakingStart = "matchmaking_start";
    public const string MatchmakingCancel = "matchmaking_cancel";
    public const string GameAction = "game_action";
    public const string UseStamp = "use_stamp";
    public const string Ping = "ping";
    public const string NpcBattleStart = "npc_battle_start";
    public const string SpectateJoin = "spectate_join";
    public const string SpectateLeave = "spectate_leave";
    public const string SpectateStamp = "spectate_stamp";
}

